/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.ui_Xe;

import edu.poly.model.xe.dao.xeDao;
import edu.poly.model.xe.modelXe;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class editXeForm extends javax.swing.JFrame {
    
    
    /**
     * Creates new form editXe
     */
    public editXeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        txtMaXe = new javax.swing.JTextField();
        txtSoMay = new javax.swing.JTextField();
        txtSoKhung = new javax.swing.JTextField();
        txtSoCho = new javax.swing.JTextField();
        txtHang = new javax.swing.JTextField();
        txtMaLoaiXe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaLuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTinhTrangXe = new javax.swing.JTextField();
        txtTimeStartTT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTimeEndTT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGiaThueGio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGiaThueNgay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGiaThueThang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTienPhat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        ád = new javax.swing.JTextField();
        btnEditShowXe = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnReSet = new javax.swing.JButton();
        txtBienSoXe = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnReSet1 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaXeEdit1 = new javax.swing.JTextField();
        btnEditShowXe1 = new javax.swing.JButton();
        txtHang1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTenXe1 = new javax.swing.JTextField();
        txtMaLoaiXe1 = new javax.swing.JTextField();
        txtTimeEndTT1 = new javax.swing.JTextField();
        txtMaXe1 = new javax.swing.JTextField();
        txtMaLuc1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtGiaThueGio1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtTinhTrangXe1 = new javax.swing.JTextField();
        txtTimeStartTT1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtSoKhung1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtBienSoXe1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtGiaThueNgay1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtGiaThueThang1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtTienPhat1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtSoMay1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtSoCho1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Sửa thông tin xe");

        jLabel18.setText("Giá xe thuê theo ngày :");

        jLabel20.setText("Tiền phạt trể ngày :");

        jLabel5.setText("Mã xe :");

        jLabel6.setText("Tên xe :");

        jLabel7.setText("Mã loại :");

        txtTinhTrangXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhTrangXeActionPerformed(evt);
            }
        });

        txtTimeStartTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeStartTTActionPerformed(evt);
            }
        });

        jLabel8.setText("Thời gian kết thúc tình trạng :");

        txtTimeEndTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeEndTTActionPerformed(evt);
            }
        });

        jLabel9.setText("Thời gian bắt đầu tình trạng :");

        txtGiaThueGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThueGioActionPerformed(evt);
            }
        });

        jLabel10.setText("Số chỗ : ");

        txtGiaThueNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThueNgayActionPerformed(evt);
            }
        });

        jLabel11.setText("Tình trạng xe :");

        txtGiaThueThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThueThangActionPerformed(evt);
            }
        });

        jLabel12.setText("Mã lực :");

        txtTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienPhatActionPerformed(evt);
            }
        });

        jLabel13.setText("Số khung :");

        jLabel14.setText("Hãng :");

        jLabel15.setText("Số máy :");

        jLabel16.setText("Giá xe thuê theo tháng :");

        jLabel17.setText("Giá xe thuê theo giờ :");

        jLabel2.setText("Nhập mã xe cần sửa :");

        btnEditShowXe.setText("Hiển thị");
        btnEditShowXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditShowXeActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu thay đổi");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReSet.setText("Đặt lại");

        txtBienSoXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBienSoXeActionPerformed(evt);
            }
        });

        jLabel21.setText("Biển số xe :");

        btnReSet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnReSet1.setText("Đặt lại");

        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnSave1.setText("Lưu thay đổi");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Sửa thông tin xe");

        jLabel4.setText("Nhập mã xe cần sửa :");

        btnEditShowXe1.setText("Hiển thị");
        btnEditShowXe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditShowXe1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Thời gian kết thúc tình trạng :");

        txtTimeEndTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeEndTT1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Thời gian bắt đầu tình trạng :");

        jLabel23.setText("Mã loại :");

        txtGiaThueGio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThueGio1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Tình trạng xe :");

        jLabel25.setText("Giá xe thuê theo giờ :");

        txtTinhTrangXe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhTrangXe1ActionPerformed(evt);
            }
        });

        txtTimeStartTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeStartTT1ActionPerformed(evt);
            }
        });

        jLabel26.setText("Số khung :");

        jLabel27.setText("Mã xe :");

        jLabel28.setText("Tên xe :");

        txtBienSoXe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBienSoXe1ActionPerformed(evt);
            }
        });

        jLabel29.setText("Biển số xe :");

        txtGiaThueNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThueNgay1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Giá xe thuê theo ngày :");

        txtGiaThueThang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThueThang1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Tiền phạt trể ngày :");

        txtTienPhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienPhat1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Giá xe thuê theo tháng :");

        jLabel33.setText("Số chỗ : ");

        jLabel34.setText("Mã lực :");

        jLabel35.setText("Hãng :");

        jLabel36.setText("Số máy :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSoCho, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHang, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel11))
                                            .addComponent(jLabel8)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTimeEndTT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaThueGio, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTinhTrangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimeStartTT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaThueNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaThueThang, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ád, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditShowXe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(298, 298, 298))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(343, 343, 343)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaXeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEditShowXe1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel23)
                                                    .addComponent(jLabel35))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtMaLoaiXe1)
                                                    .addComponent(txtHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel24))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTimeEndTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTinhTrangXe1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTimeStartTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(13, 13, 13)
                                                        .addComponent(jLabel25))
                                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtGiaThueGio1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtGiaThueNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtGiaThueThang1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel31)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtTienPhat1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel29)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtBienSoXe1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel26))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSoKhung1)
                                            .addComponent(txtMaXe1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel34))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaLuc1)
                                            .addComponent(txtTenXe1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoMay1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSoCho1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave1)
                                .addGap(18, 18, 18)
                                .addComponent(btnReSet1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnReSet)
                                .addGap(49, 49, 49)
                                .addComponent(btnExit)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ád, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditShowXe))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(txtTinhTrangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtTimeStartTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimeEndTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaThueGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaThueNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaThueThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(19, 19, 19)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnReSet)
                            .addComponent(btnExit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave1)
                            .addComponent(btnReSet1))))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaXeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditShowXe1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaXe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoKhung1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenXe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtSoMay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLuc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(txtSoCho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLoaiXe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtTinhTrangXe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtTimeStartTT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimeEndTT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaThueGio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaThueNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaThueThang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienPhat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBienSoXe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTinhTrangXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhTrangXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinhTrangXeActionPerformed

    private void txtTimeStartTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeStartTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeStartTTActionPerformed

    private void txtTimeEndTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeEndTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeEndTTActionPerformed

    private void txtGiaThueGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThueGioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThueGioActionPerformed

    private void txtGiaThueNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThueNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThueNgayActionPerformed

    private void txtGiaThueThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThueThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThueThangActionPerformed

    private void txtTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienPhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienPhatActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
//        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    
    private void btnEditShowXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditShowXeActionPerformed
//        try {
//            xeDao dao = new xeDao();
//            modelXe mdXe = dao.findByMaxeEditTxt(ád.getText());
//            
//            // kiểm tra mã xe đúng theo yêu cầu thì hiển thị lên TextFiel
//            if (mdXe != null) {
//                txtMaXe.setText(mdXe.getMaXe());
//                txtTenXe.setText(mdXe.getTenXe());
//                txtSoKhung.setText(mdXe.getSoKhung());
//                txtSoMay.setText(mdXe.getSoMay());
//                txtMaLuc.setText(String.format("%d" , mdXe.getMaLuc()));
//                txtSoCho.setText(String.format("%d" , mdXe.getSoCho()));
//                txtGiaThueThang.setText(String.format("%d" , mdXe.getGiaThueXeTheoThang()));
//                txtGiaThueNgay.setText(String.format("%d" , mdXe.getGiaThueXeTheoNgay()));
//                txtGiaThueGio.setText(String.format("%d" , mdXe.getGiaThueXeTheoGio()));
//                txtTienPhat.setText(String.format("%d" , mdXe.getTienPhat()));
//                txtHang.setText(mdXe.getHang());
//                txtTinhTrangXe.setText(mdXe.getTinhTrangXe());
//                txtTimeStartTT.setText(mdXe.getThoiGianBatDauTinhTrang());
//                txtTimeEndTT.setText(mdXe.getThoiGianKetThucTinhTrang());
//                txtMaLoaiXe.setText(mdXe.getMaLoaiXe());
//                txtBienSoXe.setText(mdXe.getBienSoXe());
//            }else{
//                JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra lại trường tìm kiếm !");
//            }
//            
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Lỗi");
//        }
    }//GEN-LAST:event_btnEditShowXeActionPerformed

    private void txtBienSoXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBienSoXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBienSoXeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
//        try {
//            //upde dữ liệu vào database
//            modelXe mdXe = new modelXe();
//            mdXe.setMaXe(txtMaXe.getText());
//            mdXe.setTenXe(txtTenXe.getText());
//            mdXe.setSoKhung(txtSoKhung.getText());
//            mdXe.setSoMay(txtSoMay.getText());
//            mdXe.setMaLuc(Integer.parseInt(txtMaLuc.getText()));
//            mdXe.setHang(txtHang.getText());
//            mdXe.setSoCho(Integer.parseInt(txtSoCho.getText()));
//            mdXe.setGiaThueXeTheoGio(Integer.parseInt(txtGiaThueGio.getText()));
//            mdXe.setGiaThueXeTheoNgay(Integer.parseInt(txtGiaThueNgay.getText()));
//            mdXe.setGiaThueXeTheoThang(Integer.parseInt(txtGiaThueThang.getText()));
//            mdXe.setTienPhat(Integer.parseInt(txtTienPhat.getText()));
//            mdXe.setTinhTrangXe(txtTinhTrangXe.getText());
//            mdXe.setThoiGianBatDauTinhTrang(txtTimeStartTT.getText());
//            mdXe.setThoiGianKetThucTinhTrang(txtTimeEndTT.getText());
//            mdXe.setMaLoaiXe(txtMaLoaiXe.getText());
//            mdXe.setBienSoXe(txtBienSoXe.getText());
            
//            xeDao dao = new xeDao();
//            if (dao.update(mdXe)) {
//                JOptionPane.showMessageDialog(this, "Lưu thành công !");
//                
//            }else{
//                JOptionPane.showMessageDialog(this, "Thêm xe bị lỗi vui lòng kiểm tra lại !");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Lỗi");
//        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
//        try {
//            //upde dữ liệu vào database
//            modelXe mdXe = new modelXe();
//            mdXe.setMaXe(txtMaXe.getText());
//            mdXe.setTenXe(txtTenXe.getText());
//            mdXe.setSoKhung(txtSoKhung.getText());
//            mdXe.setSoMay(txtSoMay.getText());
//            mdXe.setMaLuc(Integer.parseInt(txtMaLuc.getText()));
//            mdXe.setHang(txtHang.getText());
//            mdXe.setSoCho(Integer.parseInt(txtSoCho.getText()));
//            mdXe.setGiaThueXeTheoGio(Integer.parseInt(txtGiaThueGio.getText()));
//            mdXe.setGiaThueXeTheoNgay(Integer.parseInt(txtGiaThueNgay.getText()));
//            mdXe.setGiaThueXeTheoThang(Integer.parseInt(txtGiaThueThang.getText()));
//            mdXe.setTienPhat(Integer.parseInt(txtTienPhat.getText()));
//            mdXe.setTinhTrangXe(txtTinhTrangXe.getText());
//            mdXe.setThoiGianBatDauTinhTrang(txtTimeStartTT.getText());
//            mdXe.setThoiGianKetThucTinhTrang(txtTimeEndTT.getText());
//            mdXe.setMaLoaiXe(txtMaLoaiXe.getText());
//            mdXe.setBienSoXe(txtBienSoXe.getText());
//
//            xeDao dao = new xeDao();
//            if (dao.update(mdXe)) {
//                JOptionPane.showMessageDialog(this, "Lưu thành công !");
//
//            }else{
//                JOptionPane.showMessageDialog(this, "Thêm xe bị lỗi vui lòng kiểm tra lại !");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Lỗi");
//        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnEditShowXe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditShowXe1ActionPerformed
        try {
            xeDao dao = new xeDao();
            modelXe mdXe = dao.findByMaxeEditTxt(ád.getText());

            // kiểm tra mã xe đúng theo yêu cầu thì hiển thị lên TextFiel
            if (mdXe != null) {
                txtMaXe1.setText(mdXe.getMaXe());
                txtTenXe1.setText(mdXe.getTenXe());
                txtSoKhung1.setText(mdXe.getSoKhung());
                txtSoMay1.setText(mdXe.getSoMay());
                txtMaLuc1.setText(String.format("%d" , mdXe.getMaLuc()));
                txtSoCho1.setText(String.format("%d" , mdXe.getSoCho()));
                txtGiaThueThang1.setText(String.format("%d" , mdXe.getGiaThueXeTheoThang()));
                txtGiaThueNgay1.setText(String.format("%d" , mdXe.getGiaThueXeTheoNgay()));
                txtGiaThueGio1.setText(String.format("%d" , mdXe.getGiaThueXeTheoGio()));
                txtTienPhat1.setText(String.format("%d" , mdXe.getTienPhat()));
                txtHang1.setText(mdXe.getHang());
                txtTinhTrangXe1.setText(mdXe.getTinhTrangXe());
                txtTimeStartTT1.setText(mdXe.getThoiGianBatDauTinhTrang());
                txtTimeEndTT1.setText(mdXe.getThoiGianKetThucTinhTrang());
                txtMaLoaiXe1.setText(mdXe.getMaLoaiXe());
                txtBienSoXe1.setText(mdXe.getBienSoXe());
            }else{
                JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra lại trường tìm kiếm !");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
    }//GEN-LAST:event_btnEditShowXe1ActionPerformed

    private void txtTimeEndTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeEndTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeEndTT1ActionPerformed

    private void txtGiaThueGio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThueGio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThueGio1ActionPerformed

    private void txtTinhTrangXe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhTrangXe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinhTrangXe1ActionPerformed

    private void txtTimeStartTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeStartTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeStartTT1ActionPerformed

    private void txtBienSoXe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBienSoXe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBienSoXe1ActionPerformed

    private void txtGiaThueNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThueNgay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThueNgay1ActionPerformed

    private void txtGiaThueThang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThueThang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThueThang1ActionPerformed

    private void txtTienPhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienPhat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienPhat1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editXeForm().setVisible(true);
//                final editXeForm frame = new editXeForm();
//                frame.setDefaultCloseOperation(frame.DO_NOTHING_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditShowXe;
    private javax.swing.JButton btnEditShowXe1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReSet;
    private javax.swing.JButton btnReSet1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtBienSoXe1;
    private javax.swing.JTextField txtGiaThueGio;
    private javax.swing.JTextField txtGiaThueGio1;
    private javax.swing.JTextField txtGiaThueNgay;
    private javax.swing.JTextField txtGiaThueNgay1;
    private javax.swing.JTextField txtGiaThueThang;
    private javax.swing.JTextField txtGiaThueThang1;
    private javax.swing.JTextField txtHang;
    private javax.swing.JTextField txtHang1;
    private javax.swing.JTextField txtMaLoaiXe;
    private javax.swing.JTextField txtMaLoaiXe1;
    private javax.swing.JTextField txtMaLuc;
    private javax.swing.JTextField txtMaLuc1;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtMaXe1;
    private javax.swing.JTextField txtMaXeEdit1;
    private javax.swing.JTextField txtSoCho;
    private javax.swing.JTextField txtSoCho1;
    private javax.swing.JTextField txtSoKhung;
    private javax.swing.JTextField txtSoKhung1;
    private javax.swing.JTextField txtSoMay;
    private javax.swing.JTextField txtSoMay1;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTenXe1;
    private javax.swing.JTextField txtTienPhat;
    private javax.swing.JTextField txtTienPhat1;
    private javax.swing.JTextField txtTimeEndTT;
    private javax.swing.JTextField txtTimeEndTT1;
    private javax.swing.JTextField txtTimeStartTT;
    private javax.swing.JTextField txtTimeStartTT1;
    private javax.swing.JTextField txtTinhTrangXe;
    private javax.swing.JTextField txtTinhTrangXe1;
    private javax.swing.JTextField ád;
    // End of variables declaration//GEN-END:variables
}
