/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.ui_Xe;

import javax.swing.table.DefaultTableModel;


import edu.poly.model.xe.dao.xeDao;
import edu.poly.model.xe.modelXe;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author QUANGC
 */
public class showXePanel extends javax.swing.JPanel {

    private addXePanel AddXePanel;
    private editXePanel editXePanel;
    DefaultTableModel model = null;
    /**
     * Creates new form showXePanel
     */
    public showXePanel() {
        initComponents();
        
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Mã xe",
            "Tên xe",
            "Số khung",
            "Số máy",
            "Mã lực",
            "Hãng",
            "Số chỗ",
            "Giá thuê xe theo giờ",
            "Giá thue xe theo ngày",
            "Giá thuê xe theo tháng",
            "Tiền phạt",
            "Tình trạng xe",
            "Thời gian bắt đầu tình trạng",
            "Thời gian kết thúc tình trạng",
            "Mã loại xe",
            "Biển số xe"
        });// đặt tiêu đề cho cột
        tblSearchXe.setModel(model); //set dữ liệu cho bảng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowAllXe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchXe = new javax.swing.JTable();
        btnXeRepair = new javax.swing.JButton();
        btnShowReady = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSeachXe_tenXe = new javax.swing.JTextField();
        btnSearchXe_tenXea = new javax.swing.JButton();
        btnShowXeOn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDeteleMaXe = new javax.swing.JTextField();
        btnResetDeleteXe = new javax.swing.JButton();
        btnDeleteXoaXe = new javax.swing.JButton();

        btnShowAllXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/allxe.png"))); // NOI18N
        btnShowAllXe.setText("Tất cả các xe");
        btnShowAllXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllXeActionPerformed(evt);
            }
        });

        tblSearchXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Xe", "Tên xe", "Số khung", "Số máy", "Phân khối", "Hãng", "Tg bắt đầu tình trạng", "Tg kết thúc tình trạng", "Tình trạng xe", "Số chỗ", "Giá thuê giờ", "Giá thuê ngày", "Giá thuê tháng", "Tiền phạt trễ ngày", "Mã loại xe", "Biển số xe"
            }
        ));
        jScrollPane1.setViewportView(tblSearchXe);

        btnXeRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/sc.png"))); // NOI18N
        btnXeRepair.setText("Xe đang sửa chữa");
        btnXeRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXeRepairActionPerformed(evt);
            }
        });

        btnShowReady.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/ss.png"))); // NOI18N
        btnShowReady.setText("Xe sẵng sàng");
        btnShowReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowReadyActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm xe theo tên xe  : ");

        btnSearchXe_tenXea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/search1.jpg"))); // NOI18N
        btnSearchXe_tenXea.setText("Tìm");
        btnSearchXe_tenXea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchXe_tenXeaActionPerformed(evt);
            }
        });

        btnShowXeOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/chothue.png"))); // NOI18N
        btnShowXeOn.setText("Xe đang cho thuê");
        btnShowXeOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowXeOnActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhập mã Xe cần xóa :");

        btnResetDeleteXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnResetDeleteXe.setText("Đặt lại");
        btnResetDeleteXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDeleteXeActionPerformed(evt);
            }
        });

        btnDeleteXoaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnDeleteXoaXe.setText("Xóa xe");
        btnDeleteXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteXoaXeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSeachXe_tenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchXe_tenXea, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDeteleMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetDeleteXe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowAllXe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowReady, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowXeOn)
                .addGap(18, 18, 18)
                .addComponent(btnXeRepair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSeachXe_tenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchXe_tenXea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteXoaXe)
                    .addComponent(txtDeteleMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnResetDeleteXe)
                    .addComponent(btnShowXeOn)
                    .addComponent(btnXeRepair)
                    .addComponent(btnShowReady)
                    .addComponent(btnShowAllXe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllXeActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.showAllXe();
            model.setRowCount(0);

            for (modelXe mdXe : list) {
                model.addRow(new Object[]{
                    mdXe.getMaXe(),
                    mdXe.getTenXe(),
                    mdXe.getSoKhung(),
                    mdXe.getSoMay(),
                    mdXe.getMaLuc(),
                    mdXe.getHang(),
                    mdXe.getSoCho(),
                    mdXe.getGiaThueXeTheoGio(),
                    mdXe.getGiaThueXeTheoNgay(),
                    mdXe.getGiaThueXeTheoThang(),
                    mdXe.getTienPhat(),
                    mdXe.getTinhTrangXe(),
                    mdXe.getThoiGianBatDauTinhTrang(),
                    mdXe.getThoiGianKetThucTinhTrang(),
                    mdXe.getMaLoaiXe(),
                    mdXe.getBienSoXe()
                });
            }
            model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi
        }
    }//GEN-LAST:event_btnShowAllXeActionPerformed

    private void btnXeRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXeRepairActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.showXeRepair();
            model.setRowCount(0);

            for (modelXe mdXe : list) {
                model.addRow(new Object[]{
                    mdXe.getMaXe(),
                    mdXe.getTenXe(),
                    mdXe.getSoKhung(),
                    mdXe.getSoMay(),
                    mdXe.getMaLuc(),
                    mdXe.getHang(),
                    mdXe.getSoCho(),
                    mdXe.getGiaThueXeTheoGio(),
                    mdXe.getGiaThueXeTheoNgay(),
                    mdXe.getGiaThueXeTheoThang(),
                    mdXe.getTienPhat(),
                    mdXe.getTinhTrangXe(),
                    mdXe.getThoiGianBatDauTinhTrang(),
                    mdXe.getThoiGianKetThucTinhTrang(),
                    mdXe.getMaLoaiXe(),
                    mdXe.getBienSoXe()
                });
            }
            model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXeRepairActionPerformed

    private void btnShowReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowReadyActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.showXeReady();
            model.setRowCount(0);

            for (modelXe mdXe : list) {
                model.addRow(new Object[]{
                    mdXe.getMaXe(),
                    mdXe.getTenXe(),
                    mdXe.getSoKhung(),
                    mdXe.getSoMay(),
                    mdXe.getMaLuc(),
                    mdXe.getHang(),
                    mdXe.getSoCho(),
                    mdXe.getGiaThueXeTheoGio(),
                    mdXe.getGiaThueXeTheoNgay(),
                    mdXe.getGiaThueXeTheoThang(),
                    mdXe.getTienPhat(),
                    mdXe.getTinhTrangXe(),
                    mdXe.getThoiGianBatDauTinhTrang(),
                    mdXe.getThoiGianKetThucTinhTrang(),
                    mdXe.getMaLoaiXe(),
                    mdXe.getBienSoXe()
                });
            }
            model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi
        }
    }//GEN-LAST:event_btnShowReadyActionPerformed

    private void btnSearchXe_tenXeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchXe_tenXeaActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.findByName(txtSeachXe_tenXe.getText());
            model.setRowCount(0);

            if (list.size()>0) {
                for (modelXe mdXe : list) {

                    model.addRow(new Object[]{
                        mdXe.getMaXe(),
                        mdXe.getTenXe(),
                        mdXe.getSoKhung(),
                        mdXe.getSoMay(),
                        mdXe.getMaLuc(),
                        mdXe.getHang(),
                        mdXe.getSoCho(),
                        mdXe.getGiaThueXeTheoGio(),
                        mdXe.getGiaThueXeTheoNgay(),
                        mdXe.getGiaThueXeTheoThang(),
                        mdXe.getTienPhat(),
                        mdXe.getTinhTrangXe(),
                        mdXe.getThoiGianBatDauTinhTrang(),
                        mdXe.getThoiGianKetThucTinhTrang(),
                        mdXe.getMaLoaiXe(),
                        mdXe.getBienSoXe()

                    });
                }
                model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi

        }

        //        try {
            //            xeDao dao = new xeDao();
            //            List<modelXe> list = dao.findByName(txtSeachXe_tenXe.getText());
            //            model.setRowCount(0);
            //
            //
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(this, "Looix");
            //        }
    }//GEN-LAST:event_btnSearchXe_tenXeaActionPerformed

    private void btnShowXeOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowXeOnActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.showXeOn();
            model.setRowCount(0);

            for (modelXe mdXe : list) {
                model.addRow(new Object[]{
                    mdXe.getMaXe(),
                    mdXe.getTenXe(),
                    mdXe.getSoKhung(),
                    mdXe.getSoMay(),
                    mdXe.getMaLuc(),
                    mdXe.getHang(),
                    mdXe.getSoCho(),
                    mdXe.getGiaThueXeTheoGio(),
                    mdXe.getGiaThueXeTheoNgay(),
                    mdXe.getGiaThueXeTheoThang(),
                    mdXe.getTienPhat(),
                    mdXe.getTinhTrangXe(),
                    mdXe.getThoiGianBatDauTinhTrang(),
                    mdXe.getThoiGianKetThucTinhTrang(),
                    mdXe.getMaLoaiXe(),
                    mdXe.getBienSoXe()
                });
            }
            model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi
        }
    }//GEN-LAST:event_btnShowXeOnActionPerformed

    private void btnDeleteXoaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteXoaXeActionPerformed

        int n =  JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa, dữ liệu bị xóa đi sẽ không thể khôi phục lại được !",
            "Thông báo !",
            JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            try {
                xeDao dao = new xeDao();
                if (dao.delete(txtDeteleMaXe.getText())) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }else{
                    txtDeteleMaXe.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Xóa không thành công ! Vui lòng kiểm tra lại !");
                }

            } catch (Exception e) {
                e.printStackTrace(); //show lỗi
                JOptionPane.showMessageDialog(this, "Error: "+ e.getMessage()); //show lỗi
            }
        }
    }//GEN-LAST:event_btnDeleteXoaXeActionPerformed

    private void btnResetDeleteXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDeleteXeActionPerformed
        try {
            txtDeteleMaXe.setText("");
            txtDeteleMaXe.setBackground(Color.WHITE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnResetDeleteXeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteXoaXe;
    private javax.swing.JButton btnResetDeleteXe;
    private javax.swing.JButton btnSearchXe_tenXea;
    private javax.swing.JButton btnShowAllXe;
    private javax.swing.JButton btnShowReady;
    private javax.swing.JButton btnShowXeOn;
    private javax.swing.JButton btnXeRepair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSearchXe;
    private javax.swing.JTextField txtDeteleMaXe;
    private javax.swing.JTextField txtSeachXe_tenXe;
    // End of variables declaration//GEN-END:variables
}
