/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.ui;

import edu.poly.Helper.databaseHelper;
import edu.poly.object.modelHopDong;
import edu.poly.object.modelTien;
import edu.poly.objectDAO.editHopDongDao;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinh
 */
public class addHopDongPanel extends javax.swing.JPanel {

    /**
     * Creates new form addHopDong
     */
    public addHopDongPanel() {
        initComponents();
        editHopDongDao.setSoLuongXe();
        loadCBX("LOAIXE", cbxMaLoaiXe);
        loadCBX("PHUKIEN", cbxMaPK);
        loadCBX("KHACHHANG", cbxSoCMND);
        loadListBox();
        loadDataTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKh = new javax.swing.JTable();
        Center = new javax.swing.JPanel();
        CenterTop = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dpkNgayLap = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        cbxSoCMND = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dpkTimeBatDauHD = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        dpkTimeKetThucHD = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        txtDiemNhanXe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiemTraXe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaGhiChu = new javax.swing.JTextArea();
        Right = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbxMaLoaiXe = new javax.swing.JComboBox<>();
        Panel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbxMaPK = new javax.swing.JComboBox<>();
        Panel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbxDatCoc = new javax.swing.JComboBox<>();
        Panel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtMaTT = new javax.swing.JTextField();
        Panel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtTienThueXe = new javax.swing.JTextField();
        Panel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtTienSuaChua = new javax.swing.JTextField();
        Panel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        Panel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        CenterBottom = new javax.swing.JPanel();
        btnXeAdd = new javax.swing.JButton();
        btnAddReset1 = new javax.swing.JButton();
        btnEditXe = new javax.swing.JButton();
        btnEditXe1 = new javax.swing.JButton();

        setLayout(new javax.swing.OverlayLayout(this));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM HỢP ĐỒNG");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        tblKh.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblKh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblKh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKh);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1116, Short.MAX_VALUE)
            .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottomLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottomLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel2.add(bottom, java.awt.BorderLayout.PAGE_END);

        Center.setLayout(new java.awt.GridLayout(2, 1));

        CenterTop.setLayout(new java.awt.GridLayout(1, 2));

        Left.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Left.setPreferredSize(new java.awt.Dimension(200, 200));
        Left.setLayout(new java.awt.GridLayout(8, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mã Hợp Đồng:     ");
        Left.add(jLabel2);
        Left.add(txtMaHD);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ngày Lập:     ");
        Left.add(jLabel3);

        dpkNgayLap.setFormats("dd/MM/yyyy");
        Left.add(dpkNgayLap);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Số CMND:     ");
        Left.add(jLabel4);

        Left.add(cbxSoCMND);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Thời gian bắt đầu HĐ:     ");
        Left.add(jLabel5);

        dpkTimeBatDauHD.setFormats("dd/MM/yyyy");
        Left.add(dpkTimeBatDauHD);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Thời gian kết thúc HĐ:     ");
        Left.add(jLabel6);

        dpkTimeKetThucHD.setFormats("dd/MM/yyyy");
        Left.add(dpkTimeKetThucHD);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Địa điểm nhận xe:     ");
        Left.add(jLabel7);
        Left.add(txtDiemNhanXe);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Địa điểm trả xe:     ");
        Left.add(jLabel8);
        Left.add(txtDiemTraXe);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ghi chú:     ");
        Left.add(jLabel9);

        tareaGhiChu.setColumns(20);
        tareaGhiChu.setRows(5);
        jScrollPane1.setViewportView(tareaGhiChu);

        Left.add(jScrollPane1);

        CenterTop.add(Left);
        Left.getAccessibleContext().setAccessibleParent(Left);

        Right.setPreferredSize(new java.awt.Dimension(200, 200));
        Right.setLayout(new java.awt.GridLayout(8, 1));

        Panel1.setLayout(new java.awt.GridLayout(1, 2));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Mã Loại Xe:     ");
        Panel1.add(jLabel10);

        Panel1.add(cbxMaLoaiXe);

        Right.add(Panel1);

        Panel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Mã Phụ Kiện:     ");
        Panel2.add(jLabel11);

        Panel2.add(cbxMaPK);

        Right.add(Panel2);

        Panel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Đặt cọc:     ");
        Panel3.add(jLabel13);

        cbxDatCoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tien", "Xe may" }));
        Panel3.add(cbxDatCoc);

        Right.add(Panel3);

        Panel4.setLayout(new java.awt.GridLayout(1, 2));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Mã Thanh Toán:     ");
        Panel4.add(jLabel12);
        Panel4.add(txtMaTT);

        Right.add(Panel4);

        Panel5.setLayout(new java.awt.GridLayout(1, 2));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Tiền Thuê Xe:     ");
        Panel5.add(jLabel14);
        Panel5.add(txtTienThueXe);

        Right.add(Panel5);

        Panel6.setLayout(new java.awt.GridLayout(1, 2));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Tiền Sửa Chửa:     ");
        Panel6.add(jLabel15);
        Panel6.add(txtTienSuaChua);

        Right.add(Panel6);

        Panel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Tổng Tiền:     ");
        Panel7.add(jLabel16);
        Panel7.add(txtTongTien);

        Right.add(Panel7);

        Panel8.setLayout(new java.awt.GridLayout(1, 4));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Mã phụ kiện:     ");
        Panel8.add(jLabel17);

        jScrollPane3.setViewportView(jList1);

        Panel8.add(jScrollPane3);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton1.setText("<<");
        jPanel1.add(jButton1);

        Panel8.add(jPanel1);

        jScrollPane4.setViewportView(jList2);

        Panel8.add(jScrollPane4);

        Right.add(Panel8);

        CenterTop.add(Right);

        Center.add(CenterTop);

        CenterBottom.setPreferredSize(new java.awt.Dimension(88, 88));

        btnXeAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnXeAdd.setText("Thêm");
        btnXeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXeAddActionPerformed(evt);
            }
        });

        btnAddReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnAddReset1.setText("Đặt lại");
        btnAddReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReset1ActionPerformed(evt);
            }
        });

        btnEditXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnEditXe.setText("Lưu thay đổi");
        btnEditXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditXeActionPerformed(evt);
            }
        });

        btnEditXe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnEditXe1.setText("Xóa");
        btnEditXe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditXe1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CenterBottomLayout = new javax.swing.GroupLayout(CenterBottom);
        CenterBottom.setLayout(CenterBottomLayout);
        CenterBottomLayout.setHorizontalGroup(
            CenterBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditXe)
                .addGap(36, 36, 36)
                .addComponent(btnEditXe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(btnAddReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        CenterBottomLayout.setVerticalGroup(
            CenterBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterBottomLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(CenterBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXeAdd)
                    .addComponent(btnAddReset1)
                    .addComponent(btnEditXe)
                    .addComponent(btnEditXe1))
                .addGap(70, 70, 70))
        );

        Center.add(CenterBottom);

        jPanel2.add(Center, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReset1ActionPerformed
        txtMaHD.setText("");
        dpkNgayLap.setDate(null);
        dpkTimeBatDauHD.setDate(null);
        dpkTimeKetThucHD.setDate(null);
        txtDiemNhanXe.setText("");
        txtDiemTraXe.setText("");
        tareaGhiChu.setText("");
        txtMaTT.setText("");
        txtTienThueXe.setText("");
        txtTienSuaChua.setText("");
        txtTongTien.setText("");
//        loadCBX("LOAIXE", cbxMaLoaiXe);
//        loadCBX("PHUKIEN", cbxMaPK);
//        loadCBX("KHACHHANG", cbxSoCMND);
    }//GEN-LAST:event_btnAddReset1ActionPerformed

    private void btnXeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXeAddActionPerformed
        if (btnXeAdd.getText() == "Thêm") {
            txtMaHD.setText("");
            dpkNgayLap.setDate(null);
            dpkTimeBatDauHD.setDate(null);
            dpkTimeKetThucHD.setDate(null);
            txtDiemNhanXe.setText("");
            txtDiemTraXe.setText("");
            tareaGhiChu.setText("");
            txtMaTT.setText("");
            txtTienThueXe.setText("");
            txtTienSuaChua.setText("");
            txtTongTien.setText("");
            btnXeAdd.setText("Lưu");
        } else if (btnXeAdd.getText() == "Lưu") {
            if (themHopDong() == 1) {
                loadDataTable();
                JOptionPane.showMessageDialog(this, "Them Hop Dong thanh cong!");
                editHopDongDao.setSoLuongXe();
                loadCBX("LOAIXE", cbxMaLoaiXe);
            } else {
                JOptionPane.showMessageDialog(this, "Hay nhap day du cac field!");
            }
        }

    }//GEN-LAST:event_btnXeAddActionPerformed

    private void tblKhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhMouseClicked
        txtMaHD.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 0)));
        try {
            dpkNgayLap.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(String.valueOf(tblKh.getValueAt(rowSelected(), 1))));
            dpkTimeBatDauHD.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(String.valueOf(tblKh.getValueAt(rowSelected(), 3))));
            dpkTimeKetThucHD.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(String.valueOf(tblKh.getValueAt(rowSelected(), 4))));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        cbxSoCMND.setSelectedItem(String.valueOf(tblKh.getValueAt(rowSelected(), 2)));
        txtDiemNhanXe.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 5)));
        txtDiemTraXe.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 6)));
        tareaGhiChu.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 7)));
        cbxMaLoaiXe.setSelectedItem(String.valueOf(tblKh.getValueAt(rowSelected(), 8)));
        cbxMaPK.setSelectedItem(String.valueOf(tblKh.getValueAt(rowSelected(), 9)));
        cbxDatCoc.setSelectedItem(String.valueOf(tblKh.getValueAt(rowSelected(), 11)));
        txtMaTT.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 12)));
        txtTienThueXe.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 13)));
        txtTienSuaChua.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 14)));
        txtTongTien.setText(String.valueOf(tblKh.getValueAt(rowSelected(), 15)));
    }//GEN-LAST:event_tblKhMouseClicked

    private void btnEditXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditXeActionPerformed
        if (capNhatHopDong() == 1) {
            loadDataTable();
            JOptionPane.showMessageDialog(this, "Cap nhat Hop Dong thanh cong!");
        } else
            JOptionPane.showMessageDialog(this, "Hay nhap day du cac field!");
    }//GEN-LAST:event_btnEditXeActionPerformed

    private void btnEditXe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditXe1ActionPerformed
        editHopDongDao editHD = new editHopDongDao();
        modelHopDong hd = new modelHopDong();
        hd.setMaHD(Integer.parseInt(txtMaHD.getText()));

        modelTien t = new modelTien();
        t.setMaTT(txtMaTT.getText());
        if (editHD.xoaHopDong(hd, t) == 1) {
            JOptionPane.showMessageDialog(this, "Xoa Hop Dong thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "Xoa Hop Dong khong thanh cong");
        }

        loadDataTable();
    }//GEN-LAST:event_btnEditXe1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultListModel listModel2 = new DefaultListModel();
        listModel2.addElement(jList1.getSelectedValuesList());
        jList2.setModel(listModel2);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JPanel CenterBottom;
    private javax.swing.JPanel CenterTop;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel6;
    private javax.swing.JPanel Panel7;
    private javax.swing.JPanel Panel8;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel bottom;
    private javax.swing.JButton btnAddReset1;
    private javax.swing.JButton btnEditXe;
    private javax.swing.JButton btnEditXe1;
    private javax.swing.JButton btnXeAdd;
    private javax.swing.JComboBox<String> cbxDatCoc;
    private javax.swing.JComboBox<String> cbxMaLoaiXe;
    private javax.swing.JComboBox<String> cbxMaPK;
    private javax.swing.JComboBox<String> cbxSoCMND;
    private org.jdesktop.swingx.JXDatePicker dpkNgayLap;
    private org.jdesktop.swingx.JXDatePicker dpkTimeBatDauHD;
    private org.jdesktop.swingx.JXDatePicker dpkTimeKetThucHD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea tareaGhiChu;
    private javax.swing.JTable tblKh;
    private javax.swing.JTextField txtDiemNhanXe;
    private javax.swing.JTextField txtDiemTraXe;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaTT;
    private javax.swing.JTextField txtTienSuaChua;
    private javax.swing.JTextField txtTienThueXe;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void loadCBX(String table, JComboBox cbx) {
        if (table == "LOAIXE") {
            String sql = "select * from " + table + " where SoLuong is not NULL";
            try {
                Connection con = databaseHelper.openConnection();
                Statement sttm = con.createStatement();
                ResultSet rs = sttm.executeQuery(sql);
                cbx.removeAllItems();
                while (rs.next()) {
                    cbx.addItem(rs.getString(2));
//                    System.out.println("combobox: " + rs.getString(1));
                }
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            String sql = "select * from " + table + "";
            try {
                Connection con = databaseHelper.openConnection();
                Statement sttm = con.createStatement();
                ResultSet rs = sttm.executeQuery(sql);
                while (rs.next()) {
                    cbx.addItem(rs.getString(1));
                }
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    int temp = 0;

    private int themHopDong() {
        try {
            java.util.Date utilDate1 = dpkNgayLap.getDate();
            java.sql.Date ngayLap = new java.sql.Date(utilDate1.getTime());
            java.util.Date utilDate2 = dpkTimeBatDauHD.getDate();
            java.sql.Date timeBatDauHD = new java.sql.Date(utilDate2.getTime());
            java.util.Date utilDate3 = dpkTimeKetThucHD.getDate();
            java.sql.Date timeKetThucHD = new java.sql.Date(utilDate3.getTime());

            editHopDongDao editHD = new editHopDongDao();
            modelTien t = new modelTien();
            t.setMaTT(txtMaTT.getText());
            t.setTienThueXe(Float.parseFloat(txtTienThueXe.getText()));
            t.setTienSuaChua(Float.parseFloat(txtTienSuaChua.getText()));
            t.setTongTien(Float.parseFloat(txtTongTien.getText()));

            modelHopDong hd = new modelHopDong();
            hd.setMaHD(Integer.parseInt(txtMaHD.getText()));
            hd.setNgayLap((Date) ngayLap);
            hd.setSoCMND(Integer.parseInt(cbxSoCMND.getSelectedItem().toString()));
            hd.setThoiGianBatDauHD((Date) timeBatDauHD);
            hd.setThoiGianKetThucHD((Date) timeKetThucHD);
            hd.setDiaDiemNhanXe(txtDiemNhanXe.getText());
            hd.setDiaDiemTraXe(txtDiemTraXe.getText());
            hd.setGhiChu(tareaGhiChu.getText());
            hd.setMaLoaiXe(editHD.convertLoaiXeToMaLoaiXe(cbxMaLoaiXe.getSelectedItem().toString()));
            hd.setMaPK(cbxMaPK.getSelectedItem().toString());
            hd.setMaTT(txtMaTT.getText());
            hd.setDatCoc(cbxDatCoc.getSelectedItem().toString());
//            System.out.println("in loi: " + cbxMaLoaiXe.getSelectedItem().toString() + "hehe");
            editHD.insertHopDong(hd, t);

            temp = 1;

        } catch (Exception e) {
            e.printStackTrace();
            temp = 0;
        }
        return temp;
    }

    private void loadDataTable() {
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{"Ma HD", "Ngay Lap", "so CMND", "Thoi gian bat dau HD", "Thoi gian ket thuc HD", "Dia diem nhan xe", "Dia diem tra xe", "Ghi chu", "Ma loai xe", "Ma PK", "Ma TT", "Dat coc", "Ma TT", "Tien thue xe", "Tien sua chua", "Tong tien", "Ghi chu"}, 0) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            String sql = "select * from HOPDONG hd join TIEN t on hd.MaThanhToan=t.MaThanhToan";
            Statement st = databaseHelper.openConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                int maHD = rs.getInt(1);
                Date ngayLap = rs.getDate(2);
                int soCMND = rs.getInt(3);
                Date thoiGianBatDauHD = rs.getDate(4);
                Date thoiGianKetThucHD = rs.getDate(5);
                String diaDiemNhanXe = rs.getString(6);
                String diaDiemTraXe = rs.getString(7);
                String ghiChu1 = rs.getString(8);
                String maLoaiXe = rs.getString(9);
                String maPK = rs.getString(10);
                String maTT1 = rs.getString(11);
                String datCoc = rs.getString(12);
                String maTT2 = rs.getString(13);
                float tienThueXe = rs.getFloat(14);
                float tienSuaChua = rs.getFloat(15);
                float tongTien = rs.getFloat(16);
                String ghiChu2 = rs.getString(17);
                model.addRow(new Object[]{maHD, ngayLap, soCMND, thoiGianBatDauHD, thoiGianKetThucHD, diaDiemNhanXe, diaDiemTraXe, ghiChu1, maLoaiXe, maPK, maTT1, datCoc, maTT2, tienThueXe, tienSuaChua, tongTien, ghiChu2});

            }
            tblKh.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private int rowSelected() {
        int row = tblKh.getSelectedRow();
        return row;
    }

    private int capNhatHopDong() {
        try {
            java.util.Date utilDate1 = dpkNgayLap.getDate();
            java.sql.Date ngayLap = new java.sql.Date(utilDate1.getTime());
            java.util.Date utilDate2 = dpkTimeBatDauHD.getDate();
            java.sql.Date timeBatDauHD = new java.sql.Date(utilDate2.getTime());
            java.util.Date utilDate3 = dpkTimeKetThucHD.getDate();
            java.sql.Date timeKetThucHD = new java.sql.Date(utilDate3.getTime());

            editHopDongDao editHD = new editHopDongDao();
            modelTien t = new modelTien();
            t.setMaTT(txtMaTT.getText());
            t.setTienThueXe(Float.parseFloat(txtTienThueXe.getText()));
            t.setTienSuaChua(Float.parseFloat(txtTienSuaChua.getText()));
            t.setTongTien(Float.parseFloat(txtTongTien.getText()));

            modelHopDong hd = new modelHopDong();
            hd.setMaHD(Integer.parseInt(txtMaHD.getText()));
            hd.setNgayLap((Date) ngayLap);
            hd.setSoCMND(Integer.parseInt(cbxSoCMND.getSelectedItem().toString()));
            hd.setThoiGianBatDauHD((Date) timeBatDauHD);
            hd.setThoiGianKetThucHD((Date) timeKetThucHD);
            hd.setDiaDiemNhanXe(txtDiemNhanXe.getText());
            hd.setDiaDiemTraXe(txtDiemTraXe.getText());
            hd.setGhiChu(tareaGhiChu.getText());
            hd.setMaLoaiXe(cbxMaLoaiXe.getSelectedItem().toString());
            hd.setMaPK(cbxMaPK.getSelectedItem().toString());
            hd.setMaTT(txtMaTT.getText());
            hd.setDatCoc(cbxDatCoc.getSelectedItem().toString());

            editHD.updateHopDong(hd, t);
            temp = 1;

        } catch (Exception e) {
            e.printStackTrace();
            temp = 0;
        }
        return temp;
    }

    private void loadListBox() {
        DefaultListModel listModel1 = new DefaultListModel();
        try {
            String sql = "select * from LOAIPHUKIEN where SoLuong is not NULL";
            Connection con = databaseHelper.openConnection();
            Statement sttm = con.createStatement();
            ResultSet rs = sttm.executeQuery(sql);
            while (rs.next()) {
                listModel1.addElement(rs.getString(2));
            }
            jList1.setModel(listModel1);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
