/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.ui;

import edu.poly.Helper.notificationError;
import edu.poly.objectDAO.khachHangDAO;
import edu.poly.object.modelKhachHang;
import java.awt.Color;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author QUANGC
 */
public class KhachHangPanel extends javax.swing.JPanel {
    DefaultTableModel tblModel = null;
    /**
     * Creates new form demo
     */
    public KhachHangPanel() {
        initComponents();
        
        initTable();
        loadDataToTable();
        setEnabledOff();
        setEnabledEventOFF();
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{
            "Số CMND",
            "Họ và Tên",
            "Năm Sinh",
            "Số GPLX",
            "Ghi chú"
        });// đặt tiêu đề cho cột
        tblKhachHang.setModel(tblModel); //set dữ liệu cho bảng
    }
        private void loadDataToTable(){
        try {
            khachHangDAO dao = new khachHangDAO();
            List<modelKhachHang> list = dao.showAllKhachHang();
            tblModel.setRowCount(0);
                for (modelKhachHang mdKhachHang : list) {

                    tblModel.addRow(new Object[]{
                        mdKhachHang.getSoCMND(),
                        mdKhachHang.getHoTen(),
                        mdKhachHang.getNamSinh(),
                        mdKhachHang.getSoGPLX(),
                        mdKhachHang.getGhiChu()

                    });
                
                tblModel.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnResetSave = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtHoTen = new javax.swing.JTextField();
        txtCmnd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtSoGPLX = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dpkNamSinh = new org.jdesktop.swingx.JXDatePicker();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnDel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel1 = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Họ và Tên :");

        btnResetSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnResetSave.setText("Tạo mới");
        btnResetSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnResetSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSaveActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnSave.setText("Thêm");
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoTenKeyPressed(evt);
            }
        });

        txtCmnd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCmndKeyPressed(evt);
            }
        });

        jLabel2.setText("Số CMND :");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        jLabel4.setText("Số GPLX :");

        jLabel5.setText("Ghi chú :");

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/edit-20.png"))); // NOI18N
        btnUpdate.setText("Lưu thay đổi");
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtSoGPLX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoGPLXKeyPressed(evt);
            }
        });

        jLabel6.setText("Ngày tháng năm Sinh :");

        dpkNamSinh.setFormats("dd/MM/yyyy");

        jLabel22.setText("Thêm và sửa thông tin Khách Hàng");

        jLabel23.setText("Bảng Điều khiển");

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/edit-20.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnDel1.setText("Xóa");
        btnDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel1ActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/huy-18.jpg"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHoTen)
                                            .addComponent(dpkNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoGPLX, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnResetSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuy)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dpkNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoGPLX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnResetSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDel)))
                .addGap(17, 17, 17)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhachHang);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel21.setText("Quản lý Khách hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSaveActionPerformed
        txtCmnd.setText("");
        txtCmnd.setBackground(Color.white);
        txtGhiChu.setText("");
        txtHoTen.setText("");
        txtHoTen.setBackground(Color.white);
        txtSoGPLX.setText("");
        txtSoGPLX.setBackground(Color.white);
        dpkNamSinh.setDate(null);
    }//GEN-LAST:event_btnResetSaveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            //-------------báo lỗi-------------
            StringBuilder sb = new StringBuilder();
            
            notificationError.DataAvailable(txtCmnd, sb, "Trường số CMND không thể bỏ trống !");
            notificationError.DataAvailable(txtHoTen, sb, "Trường họ tên không thể bỏ trống !");
            notificationError.DataAvailable(txtSoGPLX, sb, "Trường số GPLX không thể bỏ trống !");
            
            // Hiển thị thông báo lỗi đã được đặt sẵn
            if (sb.length()>0) {
                JOptionPane.showMessageDialog(this, sb.toString());
                return;
            }
            //--------------------------------------------

            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc thêm Khách hàng ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
            java.util.Date utilDate = dpkNamSinh.getDate();
            java.sql.Date namSinh = new java.sql.Date(utilDate.getTime());

            modelKhachHang mdKH = new modelKhachHang();
            mdKH.setSoCMND(Integer.parseInt(txtCmnd.getText()));
            mdKH.setHoTen(txtHoTen.getText());
            mdKH.setGhiChu(txtGhiChu.getText());
            mdKH.setSoGPLX(Integer.parseInt(txtSoGPLX.getText()));
            mdKH.setNamSinh((Date) namSinh);
            
                khachHangDAO dao = new khachHangDAO();
                if (dao.insert(mdKH)){
                    JOptionPane.showMessageDialog(this, "Thêm khách hàng thàng công !");
                    btnResetSaveActionPerformed(evt);
                    loadDataToTable();
                    setEnabledOff();
                    setEnabledEventOFF();
                    setEnabledManageON();
                }else{
                    JOptionPane.showMessageDialog(this, "Thêm khách thất bại. Vui lòng kiểm tra lại ! !");
                }
            }
            if(n == JOptionPane.NO_OPTION){
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ! ");
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCmndKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCmndKeyPressed
        char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtCmnd.setEditable(false);
        }else{
            txtCmnd.setEditable(true);
        }
    }//GEN-LAST:event_txtCmndKeyPressed

    private void txtHoTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyPressed
        char c=evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c) ) {
            txtHoTen.setEditable(true);
        }else{
            txtHoTen.setEditable(false);   
        }
        
        int position = txtHoTen.getCaretPosition();
        txtHoTen.setText(txtHoTen.getText().toUpperCase());
        txtHoTen.setCaretPosition(position);
    }//GEN-LAST:event_txtHoTenKeyPressed

    private void txtSoGPLXKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoGPLXKeyPressed
        char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtSoGPLX.setEditable(false);
        }else{
            txtSoGPLX.setEditable(true);
        }
    }//GEN-LAST:event_txtSoGPLXKeyPressed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            java.util.Date utilDate = dpkNamSinh.getDate();
            java.sql.Date namSinh = new java.sql.Date(utilDate.getTime());

            modelKhachHang mdKH = new modelKhachHang();
            mdKH.setSoCMND(Integer.parseInt(txtCmnd.getText()));
            mdKH.setHoTen(txtHoTen.getText());
            mdKH.setGhiChu(txtGhiChu.getText());
            mdKH.setSoGPLX(Integer.parseInt(txtSoGPLX.getText()));
            mdKH.setNamSinh((Date) namSinh);

            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc cập nhật thông tin khách hàng ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
                khachHangDAO dao = new khachHangDAO();
                if (dao.update(mdKH)){
                    JOptionPane.showMessageDialog(this, "Cập nhật khách hàng thàng công !");
                    btnResetSaveActionPerformed(evt);
                    loadDataToTable();
                    setEnabledOff();
                    setEnabledEventOFF();
                    setEnabledManageON();
                }else{
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại. Vui lòng kiểm tra lại ! !");
                }
            }
            if(n == JOptionPane.NO_OPTION){
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ! ");
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {
            
            //-------------báo lỗi-------------
            StringBuilder sb = new StringBuilder();
            
            notificationError.DataAvailable(txtCmnd, sb, "Trường số CMND không thể bỏ trống !");
            
            // Hiển thị thông báo lỗi đã được đặt sẵn
            if (sb.length()>0) {
                JOptionPane.showMessageDialog(this, sb.toString());
                return;
            }
            //--------------------------------------------
            
            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc xóa thông tin khách hàng ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
                
                modelKhachHang mdKH = new modelKhachHang();
                mdKH.setSoCMND(Integer.parseInt(txtCmnd.getText()));
                
                khachHangDAO dao = new khachHangDAO();
                if (dao.delete(mdKH)){
                    JOptionPane.showMessageDialog(this, "Xóa khách hàng thàng công !");
                    btnResetSaveActionPerformed(evt);
                    loadDataToTable();
                    
                    setEnabledOff();
                    setEnabledEventOFF();
                    setEnabledManageON();
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa thất bại. Vui lòng kiểm tra lại ! !");
                }
            }
            if(n == JOptionPane.NO_OPTION){
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ! ");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        try {
            txtCmnd.setText(String.valueOf(tblKhachHang.getValueAt(rowSelected(), 0)));
            txtHoTen.setText(String.valueOf(tblKhachHang.getValueAt(rowSelected(), 1)));
            dpkNamSinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(String.valueOf(tblKhachHang.getValueAt(rowSelected(), 2))));
            txtSoGPLX.setText(String.valueOf(tblKhachHang.getValueAt(rowSelected(), 3)));
            txtGhiChu.setText(String.valueOf(tblKhachHang.getValueAt(rowSelected(), 4)));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ! ");
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setEnabledOn();
        btnResetSaveActionPerformed(evt);
        btnDel1.setEnabled(false);
        btnEdit.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDel.setEnabled(false);
        btnResetSave.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        setEnabledOff();
        setEnabledEventOFF();
        setEnabledManageON();
        btnResetSaveActionPerformed(evt);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setEnabledOn();
        btnDel1.setEnabled(false);
        btnAdd.setEnabled(false);
        btnResetSave.setEnabled(true);
        btnUpdate.setEnabled(true);
        txtCmnd.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel1ActionPerformed
        btnDel.setEnabled(true);
        setEnabledOn();
        btnEdit.setEnabled(false);
        btnAdd.setEnabled(false);
    }//GEN-LAST:event_btnDel1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDel1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnResetSave;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private org.jdesktop.swingx.JXDatePicker dpkNamSinh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoGPLX;
    // End of variables declaration//GEN-END:variables
    
    public int rowSelected() {
        int row = tblKhachHang.getSelectedRow();
        return row;
    }
    
    public void setEnabledOff(){
        txtCmnd.setEnabled(false);
        txtGhiChu.setEnabled(false);
        txtHoTen.setEnabled(false);
        txtSoGPLX.setEnabled(false);
        dpkNamSinh.setEnabled(false);
    }
    
    public void setEnabledOn(){
        txtCmnd.setEnabled(true);
        txtGhiChu.setEnabled(true);
        txtHoTen.setEnabled(true);
        txtSoGPLX.setEnabled(true);
        dpkNamSinh.setEnabled(true);
    }
    
    public  void setEnabledEventOFF(){
        btnResetSave.setEnabled(false);
        btnSave.setEnabled(false);
        btnDel.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    public void setEnabledManageON(){
        btnAdd.setEnabled(true);
        btnDel1.setEnabled(true);
        btnEdit.setEnabled(true);
    }
}
