/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.ui_xe;

import edu.poly.Helper.notificationError;
import edu.poly.object.loaiXeDao;
import edu.poly.object.modelLoaiXe;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QUANGC
 */
public class MaLoaiXePanel extends javax.swing.JPanel {
    private byte[] personalImage;
    DefaultTableModel tblmodel = null;

    /**
     * Creates new form addXePanel
     */
    public MaLoaiXePanel() {
        initComponents();
        
//        loadCBX("LOAIXE", cbxAddMaLoaiXe, 1);
//        loadCBX2(cbxAddHang);
        
        initTable();
        loadDataToTable();
        
    }
    
    private void initTable(){
        tblmodel = new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{
            "Mã loại xe",
            "Tên loại xe"
        });// đặt tiêu đề cho cột
        tblLoaiXe.setModel(tblmodel); //set dữ liệu cho bảng
    }
    
    private void loadDataToTable(){
        try {
            loaiXeDao dao = new loaiXeDao();
            List<modelLoaiXe> list = dao.findAllMaLoai();
            tblmodel.setRowCount(0);
                for (modelLoaiXe mdLoaiXe : list) {

                    tblmodel.addRow(new Object[]{
                        mdLoaiXe.getMaLoaiXe(),
                        mdLoaiXe.getTenLoaiXe()

                    });
                
                tblmodel.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiXe = new javax.swing.JTable();
        btnResetSearch = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtSearchMaLoaiXe = new javax.swing.JTextField();
        btnShowLoaiXe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtAddMaLoaiXe = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtAddTenLoaiXe = new javax.swing.JTextField();
        btnAddLoaiXe = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtDeleteMaLoaiXe = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnDelMaLoaiXe = new javax.swing.JButton();
        btnResetDel = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        tblLoaiXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLoaiXe);

        btnResetSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnResetSearch.setText("Đặt lại");
        btnResetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSearchActionPerformed(evt);
            }
        });

        jLabel20.setText("Tìm Mã Loại Xe : ");

        btnShowLoaiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/search1.jpg"))); // NOI18N
        btnShowLoaiXe.setText("Hiển thị");
        btnShowLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLoaiXeActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm"));

        jLabel17.setText("Mã Loại Xe :");

        jLabel18.setText("Tên Loại Xe :");

        btnAddLoaiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnAddLoaiXe.setText("Thêm");
        btnAddLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLoaiXeActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnReset.setText("Đặt lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddLoaiXe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddMaLoaiXe)
                            .addComponent(txtAddTenLoaiXe))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtAddMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAddTenLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLoaiXe)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Xóa "));

        jLabel19.setText("Xóa Mã Loại Xe :");

        btnDelMaLoaiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnDelMaLoaiXe.setText("Xóa");
        btnDelMaLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelMaLoaiXeActionPerformed(evt);
            }
        });

        btnResetDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnResetDel.setText("Đặt lại");
        btnResetDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeleteMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnDelMaLoaiXe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetDel)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeleteMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelMaLoaiXe)
                    .addComponent(btnResetDel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel21.setText("Quản lý Xe - Mã loại Xe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowLoaiXe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetSearch)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel21)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtSearchMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowLoaiXe)
                            .addComponent(btnResetSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLoaiXeActionPerformed
        try {
            //-------------báo lỗi-------------
            StringBuilder sb = new StringBuilder();
            
            notificationError.DataAvailable(txtAddTenLoaiXe, sb, "Trường Tên loại Xe không thể bỏ trống !");
            notificationError.DataAvailable(txtAddMaLoaiXe, sb, "Trường Mã loại Xe không thể bỏ trống !");
            
            // Hiển thị thông báo lỗi đã được đặt sẵn
            if (sb.length()>0) {
                JOptionPane.showMessageDialog(this, sb.toString());
                return;
            }
            //--------------------------------------------

            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc thêm loại xe ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {

                //set du lieu vao database
                modelLoaiXe mdLoaiXe = new modelLoaiXe();
                mdLoaiXe.setMaLoaiXe(txtAddMaLoaiXe.getText());
                mdLoaiXe.setTenLoaiXe(txtAddTenLoaiXe.getText());

                loaiXeDao dao = new loaiXeDao();
                if (dao.insert(mdLoaiXe)) {
                    JOptionPane.showMessageDialog(this, "Thêm Loại Xe thành công !");
                    btnResetActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm Loại Xe bị lỗi vui lòng kiểm tra lại !");
                }

            }
            loadDataToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddLoaiXeActionPerformed

    private void btnResetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSearchActionPerformed
        txtSearchMaLoaiXe.setText("");
    }//GEN-LAST:event_btnResetSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtAddMaLoaiXe.setBackground(Color.white);
        txtAddMaLoaiXe.setText("");
        txtAddTenLoaiXe.setBackground(Color.white);
        txtAddTenLoaiXe.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDelMaLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelMaLoaiXeActionPerformed
        try {
            StringBuilder sb = new StringBuilder();
            notificationError.DataAvailable(txtDeleteMaLoaiXe, sb, "Bạn chưa nhập thông tin");
            // Hiển thị thông báo lỗi đã được đặt sẵn
            if (sb.length()>0) {
                JOptionPane.showMessageDialog(this, sb.toString());
                return;
            }
            
            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc xóa loại xe ?", "Thông báo !", JOptionPane.YES_NO_OPTION);

            if(n == JOptionPane.YES_OPTION){
                loaiXeDao dao = new loaiXeDao();
                if (dao.delete(txtDeleteMaLoaiXe.getText())) {
                    JOptionPane.showMessageDialog(this, "Xóa Mã Loại Xe thành công !");
                    btnResetDelActionPerformed(evt);
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa Mã Loại Xe thất bại. Vui lòng kiểm tra lại thông tin !");
                }
            }
            loadDataToTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi !");
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnDelMaLoaiXeActionPerformed

    private void btnResetDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDelActionPerformed
        txtDeleteMaLoaiXe.setBackground(Color.WHITE);
        txtDeleteMaLoaiXe.setText("");
    }//GEN-LAST:event_btnResetDelActionPerformed

    private void btnShowLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLoaiXeActionPerformed
        try {
            loaiXeDao dao = new loaiXeDao();

            List<modelLoaiXe> list = dao.findByMaLoai(txtSearchMaLoaiXe.getText());
            tblmodel.setRowCount(0);

            if (list.size()>0) {
                for (modelLoaiXe mdLoaiXe : list) {

                    tblmodel.addRow(new Object[]{
                        mdLoaiXe.getMaLoaiXe(),
                        mdLoaiXe.getTenLoaiXe()

                    });
                }
                tblmodel.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi"); // show lỗi
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnShowLoaiXeActionPerformed

//    private void ShowErrorlbl(JTextField Field,JLabel lbl, String ab){
//        try {
//            int i = Integer.parseUnsignedInt(Field.getText());
//            lbl.setText("");
//        } catch (NumberFormatException e) {
//            lbl.setText(ab);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLoaiXe;
    private javax.swing.JButton btnDelMaLoaiXe;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetDel;
    private javax.swing.JButton btnResetSearch;
    private javax.swing.JButton btnShowLoaiXe;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoaiXe;
    private javax.swing.JTextField txtAddMaLoaiXe;
    private javax.swing.JTextField txtAddTenLoaiXe;
    private javax.swing.JTextField txtDeleteMaLoaiXe;
    private javax.swing.JTextField txtSearchMaLoaiXe;
    // End of variables declaration//GEN-END:variables

//    private void loadCBX(String table, JComboBox cbx, int col) {
//        String sql = "select DISTINCT * from " + table;
//        try {
//            Connection con = databaseHelper.openConnection();
//            Statement sttm = con.createStatement();
//            ResultSet rs = sttm.executeQuery(sql);
//            while (rs.next()) {
//                cbx.addItem(rs.getString(col));
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
//    
//    
//    private void loadCBX2( JComboBox cbx) {
//        String sql = "select DISTINCT Hang from xe ";
//        try {
//            Connection con = databaseHelper.openConnection();
//            Statement sttm = con.createStatement();
//            ResultSet rs = sttm.executeQuery(sql);
//            while (rs.next()) {
//                cbx.addItem(rs.getString(1));
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
    
    
}
