/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.ui;

import edu.poly.Helper.databaseHelper;
import edu.poly.Helper.imageHelper;
import edu.poly.Helper.notificationError;
import javax.swing.table.DefaultTableModel;


import edu.poly.objectDAO.xeDao;
import edu.poly.object.modelXe;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author QUANGC
 */
public class XePanel extends javax.swing.JPanel {


    DefaultTableModel model = null;
    private byte[] personalImage;
    /**
     * Creates new form showXePanel
     */
    public XePanel() {
        initComponents();
        
        initTable();
        loadTable();
        EnabledFieldOFF();
        EnabledEventOFF();
        
        loadCBX("LOAIXE", cbxAddMaLoaiXe, 1);
        loadCBX2(cbxAddHang);
        loadCBX2(cbxFilterHang);
        
        tblSearchXe.setRowHeight(25);
        tblSearchXe.setShowGrid(true);
    }
    
    public void initTable(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Mã xe",
            "Tên xe",
            "Số khung",
            "Số máy",
            "Mã lực",
            "Hãng",
            "Số chỗ",
            "Giá thuê xe theo giờ",
            "Giá thue xe theo ngày",
            "Giá thuê xe theo tháng",
            "Tiền phạt",
            "Tình trạng xe",
            "Thời gian bắt đầu tình trạng",
            "Thời gian kết thúc tình trạng",
            "Mã loại xe",
            "Biển số xe"
        });// đặt tiêu đề cho cột
        tblSearchXe.setModel(model); //set dữ liệu cho bảng
    }

    public void loadTable(){
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.showAllXe();
            model.setRowCount(0);
            
            for (modelXe mdXe : list) {
                model.addRow(new Object[]{
                    mdXe.getMaXe(),
                    mdXe.getTenXe(),
                    mdXe.getSoKhung(),
                    mdXe.getSoMay(),
                    mdXe.getMaLuc(),
                    mdXe.getHang(),
                    mdXe.getSoCho(),
                    mdXe.getGiaThueXeTheoGio(),
                    mdXe.getGiaThueXeTheoNgay(),
                    mdXe.getGiaThueXeTheoThang(),
                    mdXe.getTienPhat(),
                    mdXe.getTinhTrangXe(),
                    mdXe.getThoiGianBatDauTinhTrang(),
                    mdXe.getThoiGianKetThucTinhTrang(),
                    mdXe.getMaLoaiXe(),
                    mdXe.getBienSoXe(),
                });
                
            }
            model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDeteleMaXe = new javax.swing.JTextField();
        btnResetDeleteXe = new javax.swing.JButton();
        btnDeleteXoaXe = new javax.swing.JButton();
        btnShowAllXe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSeachXe_tenXe = new javax.swing.JTextField();
        btnSearchXe_tenXea = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        dpkAddTimeBatDau = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        showTienPhat = new javax.swing.JLabel();
        cbxAddMaLoaiXe = new javax.swing.JComboBox<>();
        txtAddSoMay = new javax.swing.JTextField();
        cbxAddSoCho = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        showGiaGio = new javax.swing.JLabel();
        txtAddTienPhat = new javax.swing.JTextField();
        showMaLuc = new javax.swing.JLabel();
        cbxAddHang = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtAddGiaNgay = new javax.swing.JTextField();
        txtAddBienSoXe = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnResetAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAddXe = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAddSoKhung = new javax.swing.JTextField();
        showGiaThang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAddGiaGio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        showGiaNgay = new javax.swing.JLabel();
        txtAddGiaThang = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtAddMaXe = new javax.swing.JTextField();
        dpkAddTimeKetThuc = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        txtAddMaLuc = new javax.swing.JTextField();
        cbxAddTinhTrang = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtAddTenXe = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnControAdd = new javax.swing.JButton();
        btnControEdit = new javax.swing.JButton();
        btnControCancel = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearchXe = new javax.swing.JTable()
        {
            @Override

            public Component prepareRenderer (TableCellRenderer renderer, int rowIndex, int columnIndex){
                Component componenet = super.prepareRenderer(renderer, rowIndex, columnIndex);

                Object value = getModel().getValueAt(rowIndex,columnIndex);

                if(columnIndex == 11){

                    if(value.equals("Sẵn sàng"))
                    {

                        componenet.setBackground(Color.GREEN);
                        componenet.setForeground(Color.BLACK);

                    }
                    if(value.equals("Đang thuê")){

                        componenet.setBackground(Color.YELLOW);
                        componenet.setForeground(Color.BLACK);
                    }

                    if(value.equals("Sửa chữa")){

                        componenet.setBackground(Color.PINK);
                        componenet.setForeground(Color.BLACK);
                    }

                }

                else {

                    componenet.setBackground(Color.WHITE);
                    componenet.setForeground(Color.BLACK);
                }

                return componenet;
            }

        }

        ;
        btnFilter = new javax.swing.JButton();
        cbxFilterTT = new javax.swing.JComboBox<>();
        cbxFilterHang = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel3.setText("Nhập mã Xe cần xóa :");

        btnResetDeleteXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnResetDeleteXe.setText("Đặt lại");
        btnResetDeleteXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDeleteXeActionPerformed(evt);
            }
        });

        btnDeleteXoaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnDeleteXoaXe.setText("Xóa xe");
        btnDeleteXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteXoaXeActionPerformed(evt);
            }
        });

        btnShowAllXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/allxe.png"))); // NOI18N
        btnShowAllXe.setText("Tất cả các xe");
        btnShowAllXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllXeActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm xe theo tên xe  : ");

        btnSearchXe_tenXea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/search1.jpg"))); // NOI18N
        btnSearchXe_tenXea.setText("Tìm");
        btnSearchXe_tenXea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchXe_tenXeaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setText("Giá thuê theo giờ :");

        jLabel23.setText("Giá thuê theo tháng :");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/xe-null.jpg"))); // NOI18N

        btnImage.setText("Chọn ảnh");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImage)
                .addContainerGap())
        );

        dpkAddTimeBatDau.setFormats("dd/MM/yyyy");

        jLabel12.setText("Thời gian kết thúc tình trạng :");

        showTienPhat.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        showTienPhat.setForeground(new java.awt.Color(255, 0, 0));

        cbxAddSoCho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel11.setText("Thời gian bắt đầu tình trạng :");

        showGiaGio.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        showGiaGio.setForeground(new java.awt.Color(255, 0, 0));

        txtAddTienPhat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddTienPhatKeyPressed(evt);
            }
        });

        showMaLuc.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        showMaLuc.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setText("Số chỗ : ");

        txtAddGiaNgay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddGiaNgayKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setText("Thêm và sửa Xe");

        btnResetAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnResetAdd.setText("Tạo mới");
        btnResetAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Số khung :");

        jLabel16.setText("Biển số xe :");

        btnAddXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnAddXe.setText("Thêm Xe");
        btnAddXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddXeActionPerformed(evt);
            }
        });

        jLabel6.setText("Số máy :");

        showGiaThang.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        showGiaThang.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setText("Mã xe :");

        jLabel14.setText("Tiền phạt trễ ngày :");

        txtAddGiaGio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddGiaGioKeyPressed(evt);
            }
        });

        jLabel4.setText("Tên xe :");

        showGiaNgay.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        showGiaNgay.setForeground(new java.awt.Color(255, 0, 0));

        txtAddGiaThang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddGiaThangKeyTyped(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnUpdate.setText("Lưu thay đổi");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel15.setText("Mã loại xe :");

        jLabel10.setText("Tình trạng xe :");

        jLabel21.setText("Giá thuê theo ngày :");

        dpkAddTimeKetThuc.setFormats("dd/MM/yyyy");

        jLabel8.setText("Mã lực :");

        txtAddMaLuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddMaLucKeyPressed(evt);
            }
        });

        cbxAddTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sẵn sàng", "Đang thuê", "Sửa chữa" }));

        jLabel9.setText("Hãng :");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Bảng điều khiển"));

        btnControAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnControAdd.setText("Thêm");
        btnControAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControAddActionPerformed(evt);
            }
        });

        btnControEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/edit-20.png"))); // NOI18N
        btnControEdit.setText("Chỉnh Sửa");
        btnControEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControEditActionPerformed(evt);
            }
        });

        btnControCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnControCancel.setText("Hủy");
        btnControCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnControAdd)
                .addGap(18, 18, 18)
                .addComponent(btnControEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnControCancel)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnControAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnControEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnControCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAddSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAddMaXe)
                                            .addComponent(txtAddTenXe)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAddSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtAddMaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGap(51, 51, 51)
                                                    .addComponent(showMaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbxAddMaLoaiXe, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxAddSoCho, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxAddHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAddGiaGio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(showGiaGio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAddGiaNgay, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(showGiaNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(showGiaThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAddGiaThang, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(showTienPhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAddTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAddBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbxAddTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dpkAddTimeKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dpkAddTimeBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnResetAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddXe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddGiaGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtAddMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showGiaGio, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel4)
                                .addComponent(txtAddTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAddGiaNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showGiaNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddGiaThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel5)
                            .addComponent(txtAddSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showGiaThang, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAddTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtAddSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAddMaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(4, 4, 4)
                                .addComponent(showMaLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAddBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxAddTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dpkAddTimeBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dpkAddTimeKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxAddHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cbxAddSoCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxAddMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddXe)
                            .addComponent(btnResetAdd)
                            .addComponent(btnUpdate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Quản lý Xe");

        tblSearchXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSearchXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchXeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSearchXe);

        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/chothue.png"))); // NOI18N
        btnFilter.setText("Lọc");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        cbxFilterTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sẵn sàng", "Đang thuê", "Sửa chữa" }));

        jLabel18.setText("Tình trạng xe :");

        jLabel19.setText("Hãng :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSeachXe_tenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchXe_tenXea, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDeteleMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteXoaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnResetDeleteXe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxFilterHang, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxFilterTT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFilter))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnShowAllXe))))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSeachXe_tenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchXe_tenXea)
                    .addComponent(btnShowAllXe))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteXoaXe)
                    .addComponent(txtDeteleMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnResetDeleteXe)
                    .addComponent(cbxFilterHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFilterTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllXeActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.showAllXe();
            model.setRowCount(0);

            for (modelXe mdXe : list) {
                model.addRow(new Object[]{
                    mdXe.getMaXe(),
                    mdXe.getTenXe(),
                    mdXe.getSoKhung(),
                    mdXe.getSoMay(),
                    mdXe.getMaLuc(),
                    mdXe.getHang(),
                    mdXe.getSoCho(),
                    mdXe.getGiaThueXeTheoGio(),
                    mdXe.getGiaThueXeTheoNgay(),
                    mdXe.getGiaThueXeTheoThang(),
                    mdXe.getTienPhat(),
                    mdXe.getTinhTrangXe(),
                    mdXe.getThoiGianBatDauTinhTrang(),
                    mdXe.getThoiGianKetThucTinhTrang(),
                    mdXe.getMaLoaiXe(),
                    mdXe.getBienSoXe()
                });
            }
            model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi
        }
    }//GEN-LAST:event_btnShowAllXeActionPerformed

    private void btnSearchXe_tenXeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchXe_tenXeaActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.findByName(txtSeachXe_tenXe.getText());
            model.setRowCount(0);

            if (list.size()>0) {
                for (modelXe mdXe : list) {

                    model.addRow(new Object[]{
                        mdXe.getMaXe(),
                        mdXe.getTenXe(),
                        mdXe.getSoKhung(),
                        mdXe.getSoMay(),
                        mdXe.getMaLuc(),
                        mdXe.getHang(),
                        mdXe.getSoCho(),
                        mdXe.getGiaThueXeTheoGio(),
                        mdXe.getGiaThueXeTheoNgay(),
                        mdXe.getGiaThueXeTheoThang(),
                        mdXe.getTienPhat(),
                        mdXe.getTinhTrangXe(),
                        mdXe.getThoiGianBatDauTinhTrang(),
                        mdXe.getThoiGianKetThucTinhTrang(),
                        mdXe.getMaLoaiXe(),
                        mdXe.getBienSoXe()

                    });
                }
                model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi

        }
    }//GEN-LAST:event_btnSearchXe_tenXeaActionPerformed

    private void btnDeleteXoaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteXoaXeActionPerformed

        int n =  JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa, dữ liệu bị xóa đi sẽ không thể khôi phục lại được !",
            "Thông báo !",
            JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            try {
                xeDao dao = new xeDao();
                if (dao.delete(txtDeteleMaXe.getText())) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    btnResetDeleteXeActionPerformed(evt);
                }else{
                    txtDeteleMaXe.setBackground(Color.red);
                    JOptionPane.showMessageDialog(this, "Xóa không thành công ! Vui lòng kiểm tra lại !");
                }

            } catch (Exception e) {
                e.printStackTrace(); //show lỗi
                JOptionPane.showMessageDialog(this, "Error: "+ e.getMessage()); //show lỗi
            }
        }
        loadTable();
    }//GEN-LAST:event_btnDeleteXoaXeActionPerformed

    private void btnResetDeleteXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDeleteXeActionPerformed
        try {
            txtDeteleMaXe.setText("");
            txtDeteleMaXe.setBackground(Color.WHITE);
        }  catch (Exception e) {
                e.printStackTrace(); //show lỗi
                JOptionPane.showMessageDialog(this, "Error: "+ e.getMessage()); //show lỗi
            }
    }//GEN-LAST:event_btnResetDeleteXeActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        JFileChooser fChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image File (*.jpg)", "jpg");
        fChooser.setFileFilter(imageFilter);
        fChooser.setMultiSelectionEnabled(false); //chọn 1 ảnh

        int x = fChooser.showDialog(this, "Open");
        if(x == JFileChooser.APPROVE_OPTION){
            File file = fChooser.getSelectedFile(); // cho nguoi dung chi 1 file, neu nhiu thi them "s"
            try {
                ImageIcon icon = new ImageIcon(file.getPath());
                Image img = imageHelper.resize(icon.getImage(), 450, 250);
                ImageIcon resizeIcon = new ImageIcon(img);
                lblImage.setIcon(resizeIcon);
                personalImage = imageHelper.toByteArray(img, "jpg");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void txtAddTienPhatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddTienPhatKeyPressed
        ShowErrorlbl(txtAddTienPhat, showTienPhat, "Số tiền không được nhập chữ !");
    }//GEN-LAST:event_txtAddTienPhatKeyPressed

    private void txtAddGiaNgayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddGiaNgayKeyPressed
        ShowErrorlbl(txtAddGiaNgay,showGiaNgay, "Số tiền không được nhập chữ !");
    }//GEN-LAST:event_txtAddGiaNgayKeyPressed

    private void btnResetAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAddActionPerformed
        txtAddMaXe.setText("");
        txtAddMaXe.setBackground(Color.white);
        txtAddTenXe.setText("");
        txtAddTenXe.setBackground(Color.white);
        txtAddSoKhung.setText("");
        txtAddSoKhung.setBackground(Color.white);
        txtAddSoMay.setText("");
        txtAddSoMay.setBackground(Color.white);
        txtAddMaLuc.setText("");
        txtAddMaLuc.setBackground(Color.white);
        txtAddGiaGio.setText("");
        txtAddGiaGio.setBackground(Color.white);
        txtAddGiaNgay.setText("");
        txtAddGiaNgay.setBackground(Color.white);
        txtAddGiaThang.setText("");
        txtAddGiaThang.setBackground(Color.white);
        txtAddTienPhat.setText("");
        txtAddTienPhat.setBackground(Color.white);
        txtAddBienSoXe.setText("");
        txtAddBienSoXe.setBackground(Color.white);
        dpkAddTimeBatDau.setDate(null);
        dpkAddTimeKetThuc.setDate(null);
        cbxAddSoCho.setSelectedIndex(0);
        cbxAddMaLoaiXe.setSelectedIndex(0);
        cbxAddHang.setSelectedIndex(0);
        cbxAddTinhTrang.setSelectedIndex(0);
        showMaLuc.setText("");
        showGiaGio.setText("");
        showGiaNgay.setText("");
        showGiaThang.setText("");
        showTienPhat.setText("");
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/edu/poly/icon/icon/xe-null.jpg"));
        lblImage.setIcon(icon);
    }//GEN-LAST:event_btnResetAddActionPerformed

    private void btnAddXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddXeActionPerformed

        try {
            
            //-------------báo lỗi-------------
            StringBuilder sb = new StringBuilder();
            
            notificationError.DataAvailable(txtAddMaXe, sb, "Trường mã xe không thể bỏ trống !");
            notificationError.DataAvailable(txtAddTenXe, sb, "Trường tên Xe không thể bỏ trống !");
            notificationError.DataAvailable(txtAddSoKhung, sb, "Trường số khung không thể bỏ trống !");
            notificationError.DataAvailable(txtAddSoMay, sb, "Trường số máy không thể bỏ trống !");
            notificationError.DataAvailable(txtAddBienSoXe, sb, "Trường biển số Xe không thể bỏ trống !");
            notificationError.DataAvailable(txtAddMaLuc, sb, "Trường mã lực Xe không thể bỏ trống !");
            notificationError.DataAvailable(txtAddGiaGio, sb, "Trường giá thuê xe theo giờ không thể bỏ trống !");
            notificationError.DataAvailable(txtAddGiaNgay, sb, "Trường giá thuê xe theo ngày không thể bỏ trống !");
            notificationError.DataAvailable(txtAddGiaThang, sb, "Trường giá thuê xe theo tháng không thể bỏ trống !");
            notificationError.DataAvailable(txtAddTienPhat, sb, "Trường giá xe phạt trể ngày không thể bỏ trống !");
            
            // Hiển thị thông báo lỗi đã được đặt sẵn
            if (sb.length()>0) {
                JOptionPane.showMessageDialog(this, sb.toString());
                return;
            }
            //--------------------------------------------
            
            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc thêm xe ?", "Thông báo !", JOptionPane.YES_NO_OPTION);

            if (n == JOptionPane.YES_OPTION) {
                

            //set dữ liệu vào table
            java.util.Date utilDate1 = dpkAddTimeBatDau.getDate();
            java.sql.Date timeBatDau = new java.sql.Date(utilDate1.getTime());
            java.util.Date utilDate2 = dpkAddTimeKetThuc.getDate();
            java.sql.Date timeKetThuc = new java.sql.Date(utilDate2.getTime());

            modelXe mdXe = new modelXe();
            mdXe.setMaXe(txtAddMaXe.getText());
            mdXe.setTenXe(txtAddTenXe.getText());
            mdXe.setSoKhung(txtAddSoKhung.getText());
            mdXe.setSoMay(txtAddSoMay.getText());
            mdXe.setBienSoXe(txtAddBienSoXe.getText());
            mdXe.setMaLuc(Integer.parseInt(txtAddMaLuc.getText()));
            mdXe.setHang(cbxAddHang.getSelectedItem().toString());
            mdXe.setMaLoaiXe(cbxAddMaLoaiXe.getSelectedItem().toString());
            mdXe.setSoCho(Integer.parseInt(cbxAddSoCho.getSelectedItem().toString()));
            mdXe.setGiaThueXeTheoGio(Integer.parseInt(txtAddGiaGio.getText()));
            mdXe.setGiaThueXeTheoNgay(Integer.parseInt(txtAddGiaNgay.getText()));
            mdXe.setGiaThueXeTheoThang(Integer.parseInt(txtAddGiaThang.getText()));
            mdXe.setTienPhat(Integer.parseInt(txtAddTienPhat.getText()));
            mdXe.setTinhTrangXe(cbxAddTinhTrang.getSelectedItem().toString());
            mdXe.setThoiGianBatDauTinhTrang((Date) timeBatDau);
            mdXe.setThoiGianKetThucTinhTrang((Date) timeKetThuc);
            mdXe.setHinhXe(personalImage);
            
                xeDao dao = new  xeDao();
                if (dao.insert(mdXe)) {
                    JOptionPane.showMessageDialog(this, "Thêm Xe thành công !");
                    loadTable();
                    btnResetAddActionPerformed(evt);
                    EnabledFieldOFF();
                    EnabledEventOFF();
                    EnabledControlON();
                }else{
                    JOptionPane.showMessageDialog(this, "Thêm Xe thất bại ! vui lòng kiểm tra lại !");
                }
            }
            if (n == JOptionPane.NO_OPTION) {
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: Vui lòng kiểm tra lại !");
        }
    }//GEN-LAST:event_btnAddXeActionPerformed

    private void txtAddGiaGioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddGiaGioKeyPressed
        ShowErrorlbl(txtAddGiaGio,showGiaGio, "Số tiền không được nhập chữ !");
    }//GEN-LAST:event_txtAddGiaGioKeyPressed

    private void txtAddGiaThangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddGiaThangKeyTyped
        ShowErrorlbl(txtAddGiaThang,showGiaThang, "Số tiền không được nhập chữ !");
    }//GEN-LAST:event_txtAddGiaThangKeyTyped

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            java.util.Date utilDate1 = dpkAddTimeBatDau.getDate();
            java.sql.Date timeBatDau = new java.sql.Date(utilDate1.getTime());
            java.util.Date utilDate2 = dpkAddTimeKetThuc.getDate();
            java.sql.Date timeKetThuc = new java.sql.Date(utilDate2.getTime());

            modelXe mdXe = new modelXe();
            mdXe.setMaXe(txtAddMaXe.getText());
            mdXe.setTenXe(txtAddTenXe.getText());
            mdXe.setSoKhung(txtAddSoKhung.getText());
            mdXe.setSoMay(txtAddSoMay.getText());
            mdXe.setBienSoXe(txtAddBienSoXe.getText());
            mdXe.setMaLuc(Integer.parseInt(txtAddMaLuc.getText()));
            mdXe.setHang(cbxAddHang.getSelectedItem().toString());
            mdXe.setMaLoaiXe(cbxAddMaLoaiXe.getSelectedItem().toString());
            mdXe.setSoCho(Integer.parseInt(cbxAddSoCho.getSelectedItem().toString()));
            mdXe.setGiaThueXeTheoGio(Integer.parseInt(txtAddGiaGio.getText()));
            mdXe.setGiaThueXeTheoNgay(Integer.parseInt(txtAddGiaNgay.getText()));
            mdXe.setGiaThueXeTheoThang(Integer.parseInt(txtAddGiaThang.getText()));
            mdXe.setTienPhat(Integer.parseInt(txtAddTienPhat.getText()));
            mdXe.setTinhTrangXe(cbxAddTinhTrang.getSelectedItem().toString());
            mdXe.setThoiGianBatDauTinhTrang((Date) timeBatDau);
            mdXe.setThoiGianKetThucTinhTrang((Date) timeKetThuc);
            mdXe.setHinhXe(personalImage);

            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc lưu thay đổi ?", "Thông báo !", JOptionPane.YES_NO_OPTION);

            if (n == JOptionPane.YES_OPTION) {
                xeDao dao = new xeDao();
                if (dao.update(mdXe)) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công !");
                    btnResetAddActionPerformed(evt);
                    btnAddXe.setEnabled(true);
                    loadTable();
                    EnabledFieldOFF();
                    EnabledEventOFF();
                    EnabledControlON();
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Mã Xe không được thay đổi. Vui lòng kiểm tra lại !");
                }
            }
            if (n == JOptionPane.NO_OPTION) {
                return;
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi !");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtAddMaLucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddMaLucKeyPressed
        ShowErrorlbl(txtAddMaLuc,showMaLuc, "Bạn không được nhập chữ !");
        
        String checkMaLuc = txtAddMaLuc.getText();
        int length = checkMaLuc.length();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<= '9'){
            if (length<5) {
                txtAddMaLuc.setEnabled(true);
            }else{
                txtAddMaLuc.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtAddMaLucKeyPressed

    private void btnControAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControAddActionPerformed
        btnResetAddActionPerformed(evt);
        EnabledFieldON();
        btnUpdate.setEnabled(false);
        btnControEdit.setEnabled(false);
        btnResetAdd.setEnabled(true);
        btnAddXe.setEnabled(true);
    }//GEN-LAST:event_btnControAddActionPerformed

    private void btnControCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControCancelActionPerformed
        EnabledControlON();
        EnabledEventOFF();
        EnabledFieldOFF();
        btnResetAddActionPerformed(evt);
    }//GEN-LAST:event_btnControCancelActionPerformed

    private void btnControEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControEditActionPerformed
        EnabledFieldON();
        btnResetAdd.setEnabled(false);
        btnAddXe.setEnabled(false);
        btnControAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
        txtAddMaXe.setEnabled(false);
    }//GEN-LAST:event_btnControEditActionPerformed

    private void tblSearchXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchXeMouseClicked
        try {
            int row = tblSearchXe.getSelectedRow();

            if (row>=0) {
                String MaXe = (String) tblSearchXe.getValueAt(row, 0);
                xeDao dao = new xeDao();
                modelXe mdXe = dao.findByMaxeEditTxt(MaXe);

                if (mdXe != null) {
                    txtAddMaXe.setText(mdXe.getMaXe());
                    txtAddTenXe.setText(mdXe.getTenXe());
                    txtAddSoKhung.setText(mdXe.getSoKhung());
                    txtAddSoMay.setText(mdXe.getSoMay());
                    txtAddMaLuc.setText(String.format("%d" , mdXe.getMaLuc()));
                    txtAddGiaGio.setText(String.format("%d" ,mdXe.getGiaThueXeTheoGio()));
                    txtAddGiaNgay.setText(String.format("%d" ,mdXe.getGiaThueXeTheoNgay()));
                    txtAddGiaThang.setText(String.format("%d" ,mdXe.getGiaThueXeTheoThang()));
                    txtAddTienPhat.setText(String.format("%d" ,mdXe.getTienPhat()));
                    txtAddBienSoXe.setText(mdXe.getBienSoXe());
                    cbxAddHang.setSelectedItem(mdXe.getHang());
                    cbxAddMaLoaiXe.setSelectedItem(mdXe.getMaLoaiXe());
                    cbxAddSoCho.setSelectedItem(String.format("%d" , mdXe.getSoCho()));
                    cbxAddSoCho.addItem(String.format("%d", mdXe.getSoCho()));
                    cbxAddTinhTrang.setSelectedItem(mdXe.getTinhTrangXe());
                    dpkAddTimeBatDau.setDate(mdXe.getThoiGianBatDauTinhTrang());
                    dpkAddTimeKetThuc.setDate(mdXe.getThoiGianKetThucTinhTrang());
                    if(mdXe.getHinhXe() != null){
                        Image img = imageHelper.createImageFromByteArray(mdXe.getHinhXe(), "jpg");
                        lblImage.setIcon(new ImageIcon(img));
                        personalImage = mdXe.getHinhXe();
                    }else{
                        ImageIcon icon = new ImageIcon(getClass().getResource("/edu/poly/icon/icon/xe-null.jpg"));
                        lblImage.setIcon(icon);
                    }

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi !");
        }

    }//GEN-LAST:event_tblSearchXeMouseClicked

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        try {
            xeDao dao = new xeDao();

            List<modelXe> list = dao.filterXe(cbxFilterHang.getSelectedItem().toString() ,cbxFilterTT.getSelectedItem().toString());
            model.setRowCount(0);

            if (list.size()>0) {
                for (modelXe mdXe : list) {

                    model.addRow(new Object[]{
                        mdXe.getMaXe(),
                        mdXe.getTenXe(),
                        mdXe.getSoKhung(),
                        mdXe.getSoMay(),
                        mdXe.getMaLuc(),
                        mdXe.getHang(),
                        mdXe.getSoCho(),
                        mdXe.getGiaThueXeTheoGio(),
                        mdXe.getGiaThueXeTheoNgay(),
                        mdXe.getGiaThueXeTheoThang(),
                        mdXe.getTienPhat(),
                        mdXe.getTinhTrangXe(),
                        mdXe.getThoiGianBatDauTinhTrang(),
                        mdXe.getThoiGianKetThucTinhTrang(),
                        mdXe.getMaLoaiXe(),
                        mdXe.getBienSoXe()

                    });
                }
                model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Lỗi"); // show lỗi
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnFilterActionPerformed
 
    private void ShowErrorlbl(JTextField Field,JLabel lbl, String ab){
        try {
            int i = Integer.parseUnsignedInt(Field.getText());
            lbl.setText("");
        } catch (NumberFormatException e) {
            lbl.setText(ab);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddXe;
    private javax.swing.JButton btnControAdd;
    private javax.swing.JButton btnControCancel;
    private javax.swing.JButton btnControEdit;
    private javax.swing.JButton btnDeleteXoaXe;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnResetAdd;
    private javax.swing.JButton btnResetDeleteXe;
    private javax.swing.JButton btnSearchXe_tenXea;
    private javax.swing.JButton btnShowAllXe;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxAddHang;
    private javax.swing.JComboBox<String> cbxAddMaLoaiXe;
    private javax.swing.JComboBox<String> cbxAddSoCho;
    private javax.swing.JComboBox<String> cbxAddTinhTrang;
    private javax.swing.JComboBox<String> cbxFilterHang;
    private javax.swing.JComboBox<String> cbxFilterTT;
    private org.jdesktop.swingx.JXDatePicker dpkAddTimeBatDau;
    private org.jdesktop.swingx.JXDatePicker dpkAddTimeKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel showGiaGio;
    private javax.swing.JLabel showGiaNgay;
    private javax.swing.JLabel showGiaThang;
    private javax.swing.JLabel showMaLuc;
    private javax.swing.JLabel showTienPhat;
    private javax.swing.JTable tblSearchXe;
    private javax.swing.JTextField txtAddBienSoXe;
    private javax.swing.JTextField txtAddGiaGio;
    private javax.swing.JTextField txtAddGiaNgay;
    private javax.swing.JTextField txtAddGiaThang;
    private javax.swing.JTextField txtAddMaLuc;
    private javax.swing.JTextField txtAddMaXe;
    private javax.swing.JTextField txtAddSoKhung;
    private javax.swing.JTextField txtAddSoMay;
    private javax.swing.JTextField txtAddTenXe;
    private javax.swing.JTextField txtAddTienPhat;
    private javax.swing.JTextField txtDeteleMaXe;
    private javax.swing.JTextField txtSeachXe_tenXe;
    // End of variables declaration//GEN-END:variables

        private void loadCBX(String table, JComboBox cbx, int col) {
        String sql = "select DISTINCT * from " + table;
        try {
            Connection con = databaseHelper.openConnection();
            Statement sttm = con.createStatement();
            ResultSet rs = sttm.executeQuery(sql);
            while (rs.next()) {
                cbx.addItem(rs.getString(col));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    private void loadCBX2( JComboBox cbx) {
        String sql = "select DISTINCT Hang from xe ";
        try {
            Connection con = databaseHelper.openConnection();
            Statement sttm = con.createStatement();
            ResultSet rs = sttm.executeQuery(sql);
            while (rs.next()) {
                cbx.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void EnabledFieldON(){
        txtAddMaXe.setEnabled(true);
        txtAddTenXe.setEnabled(true);
        txtAddSoKhung.setEnabled(true);
        txtAddSoMay.setEnabled(true);
        txtAddMaLuc.setEnabled(true);
        txtAddGiaGio.setEnabled(true);
        txtAddGiaNgay.setEnabled(true);
        txtAddGiaThang.setEnabled(true);
        txtAddTienPhat.setEnabled(true);
        txtAddBienSoXe.setEnabled(true);
        cbxAddHang.setEnabled(true);
        cbxAddMaLoaiXe.setEnabled(true);
        cbxAddSoCho.setEnabled(true);
        cbxAddSoCho.setEnabled(true);
        cbxAddTinhTrang.setEnabled(true);
        dpkAddTimeBatDau.setEnabled(true);
        dpkAddTimeKetThuc.setEnabled(true);
        btnImage.setEnabled(true);
    }
    
    private void EnabledFieldOFF(){
        txtAddMaXe.setEnabled(false);
        txtAddTenXe.setEnabled(false);
        txtAddSoKhung.setEnabled(false);
        txtAddSoMay.setEnabled(false);
        txtAddMaLuc.setEnabled(false);
        txtAddGiaGio.setEnabled(false);
        txtAddGiaNgay.setEnabled(false);
        txtAddGiaThang.setEnabled(false);
        txtAddTienPhat.setEnabled(false);
        txtAddBienSoXe.setEnabled(false);
        cbxAddHang.setEnabled(false);
        cbxAddMaLoaiXe.setEnabled(false);
        cbxAddSoCho.setEnabled(false);
        cbxAddSoCho.setEnabled(false);
        cbxAddTinhTrang.setEnabled(false);
        dpkAddTimeBatDau.setEnabled(false);
        dpkAddTimeKetThuc.setEnabled(false);
        btnImage.setEnabled(false);
    }
    
    private void EnabledEventOFF(){
        btnResetAdd.setEnabled(false);
        btnAddXe.setEnabled(false);
        btnUpdate.setEnabled(false);
    }
    
    private void EnabledControlON(){
        btnControAdd.setEnabled(true);
        btnControEdit.setEnabled(true);
        btnControCancel.setEnabled(true);
    }
}
