/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.login;

import edu.poly.Helper.databaseHelper;
import edu.poly.objectDAO.loginDao;
import edu.poly.object.modeLogin;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QUANGC
 */
public class loginPanel extends javax.swing.JPanel {

    DefaultTableModel model = null;
    /**
     * Creates new form loginPanel
     */
    public loginPanel() {
        initComponents();
        
        initTable();
        loadTable();
        loadCBX(cbxRole);
        
        setEnabledEventOFF();
        setEnabledFieldOFF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        cbxRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtUse = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogin = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnControSave = new javax.swing.JButton();
        btnControEdit = new javax.swing.JButton();
        btnControDel = new javax.swing.JButton();
        btnControCancel = new javax.swing.JButton();

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel21.setText("Quản lý Tài khoảng đăng nhập");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/edit-20.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel3.setText("Vài trò :");

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/reset-20.png"))); // NOI18N
        btnReset.setText("Đặt lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setText("Tài khoảng :");

        jLabel2.setText("Mật Khẩu :");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoginMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLogin);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnControSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/save-20.png"))); // NOI18N
        btnControSave.setText("Thêm");
        btnControSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControSaveActionPerformed(evt);
            }
        });

        btnControEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/edit-20.png"))); // NOI18N
        btnControEdit.setText("Sửa");
        btnControEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControEditActionPerformed(evt);
            }
        });

        btnControDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/delete-20.png"))); // NOI18N
        btnControDel.setText("Xóa");
        btnControDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControDelActionPerformed(evt);
            }
        });

        btnControCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/icon/icon/huy-15.jpg"))); // NOI18N
        btnControCancel.setText("Hủy");
        btnControCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnControSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnControEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnControDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnControCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnControSave, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControDel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUse)
                            .addComponent(txtPass)
                            .addComponent(cbxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnAdd)
                            .addComponent(btnReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoginMouseClicked
        txtUse.setText(String.valueOf(tblLogin.getValueAt(rowSelected(), 0)));
        txtPass.setText(String.valueOf(tblLogin.getValueAt(rowSelected(), 1)));
        cbxRole.setSelectedItem(String.valueOf(tblLogin.getValueAt(rowSelected(), 2)));
    }//GEN-LAST:event_tblLoginMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            //set du lieu vao database
            modeLogin mdLG = new modeLogin();
            mdLG.setTaiKhoang(txtUse.getText());
            mdLG.setMatKhau(txtPass.getText());
            mdLG.setChucNang(cbxRole.getSelectedItem().toString());
            
            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc thêm tài khoảng này ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
                    loginDao dao = new loginDao();
                if (dao.insert(mdLG)) {
                    JOptionPane.showMessageDialog(this, "Thêm tài khoảng thành công !");
                    btnResetActionPerformed(evt);
                    loadTable();
                    setEnabldReset();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm tài khoảng bị lỗi vui lòng kiểm tra lại !");
                }
            }
            if (n == JOptionPane.NO_OPTION) {
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ! ");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtUse.setText("");
        txtPass.setText("");
        cbxRole.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            //set du lieu vao database
            modeLogin mdLG = new modeLogin();
            mdLG.setTaiKhoang(txtUse.getText());
            mdLG.setMatKhau(txtPass.getText());
            mdLG.setChucNang(cbxRole.getSelectedItem().toString());

            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc cập nhật thông tin tài khoảng ?", "Thông báo !", JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
                loginDao dao = new loginDao();
                if (dao.update(mdLG)){
                    JOptionPane.showMessageDialog(this, "Cập nhật tài khoảng thàng công !");
                    btnResetActionPerformed(evt);
                    loadTable();
                    setEnabldReset();
                }else{
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại. Vui lòng kiểm tra lại ! !");
                }
            }
            if(n == JOptionPane.NO_OPTION){
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ! ");
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {
            int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắc xóa tài khoảng này ?", "Thông báo !", JOptionPane.YES_NO_OPTION);

            if(n == JOptionPane.YES_OPTION){
                loginDao dao = new loginDao();
                if (dao.delete(txtUse.getText())) {
                    JOptionPane.showMessageDialog(this, "Xóatài khoảng thành công !");
                    btnResetActionPerformed(evt);
                    loadTable();
                    setEnabldReset();
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa tài khoảng thất bại. Vui lòng kiểm tra lại thông tin !");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ! ");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnControSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControSaveActionPerformed
        setEnabledFieldON();
        btnResetActionPerformed(evt);
        btnControEdit.setEnabled(false);
        btnControDel.setEnabled(false);
        btnReset.setEnabled(true);
        btnAdd.setEnabled(true);
    }//GEN-LAST:event_btnControSaveActionPerformed

    private void btnControEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControEditActionPerformed
        setEnabledFieldON();
        btnControSave.setEnabled(false);
        btnControDel.setEnabled(false);
        btnReset.setEnabled(true);
        txtUse.setEnabled(false);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_btnControEditActionPerformed

    private void btnControDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControDelActionPerformed
        setEnabledFieldON();
        btnControSave.setEnabled(false);
        btnControEdit.setEnabled(false);
        btnReset.setEnabled(true);
        btnDel.setEnabled(true);
    }//GEN-LAST:event_btnControDelActionPerformed

    private void btnControCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControCancelActionPerformed
        setEnabldReset();
    }//GEN-LAST:event_btnControCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnControCancel;
    private javax.swing.JButton btnControDel;
    private javax.swing.JButton btnControEdit;
    private javax.swing.JButton btnControSave;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblLogin;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUse;
    // End of variables declaration//GEN-END:variables

    public void initTable(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Tài Khoảng",
            "Mật khẩu",
            "Vai trò"
        });// đặt tiêu đề cho cột
        tblLogin.setModel(model); //set dữ liệu cho bảng
    }

    public void loadTable(){
        try {
            loginDao dao = new loginDao();

            List<modeLogin> list = dao.showLogin();
            model.setRowCount(0);
            
            list.forEach((mdLG) -> {
                model.addRow(new Object[]{
                    mdLG.getTaiKhoang(),
                    mdLG.getMatKhau(),
                    mdLG.getChucNang()
                });
            });
            model.fireTableDataChanged(); // cập nhật toàn bộ dữ liệu bảng (chỉ dữ liệu của bảng)

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // show lỗi
        }
    }
    
    private int rowSelected() {
        int row = tblLogin.getSelectedRow();
        return row;
    }
    
    private void loadCBX( JComboBox cbx) {
        String sql = "select DISTINCT chucNang from LOGIN ";
        try {
            Connection con = databaseHelper.openConnection();
            Statement sttm = con.createStatement();
            ResultSet rs = sttm.executeQuery(sql);
            while (rs.next()) {
                cbx.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void setEnabledEventOFF(){
        btnReset.setEnabled(false);
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDel.setEnabled(false);
    }
    
    
    private void setEnabledFieldON(){
        txtPass.setEnabled(true);
        txtUse.setEnabled(true);
        cbxRole.setEnabled(true);
    }
    
    private void setEnabledFieldOFF(){
        txtPass.setEnabled(false);
        txtUse.setEnabled(false);
        cbxRole.setEnabled(false);
    }
    
    private void setEnabledControlON(){
        btnControDel.setEnabled(true);
        btnControEdit.setEnabled(true);
        btnControSave.setEnabled(true);
    }
    
    private void setEnabldReset(){
        setEnabledEventOFF();
        setEnabledFieldOFF();
        setEnabledControlON();
    }
}
